context:
  version: 0.1.0dev20260917
  commit: b09b56c29c1e367e598b60ca266e2cc9038751e0
  sha256: f9438e8b0c8d8887c4b30b402b3b383b2cd059c9fd5c00a5e7eac8ddae24cad4

package:
  name: wezterm
  version: ${{ version }}

source:
  url: https://codeload.github.com/wezterm/wezterm/tar.gz/${{ commit }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch

build:
  number: 0
  script:
    content:
    - set "OPENSSL_DIR=%LIBRARY_PREFIX%"
    - set OPENSSL_NO_VENDOR=1
    - cargo install --locked --no-track --path wezterm-gui --root "%LIBRARY_PREFIX%"
    env:
      CARGO_HOME: ${{ env.get('CARGO_HOME', default='') }}
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - perl * *_strawberry
  - rust >=1.89.0
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  host:
  - freetype
  - harfbuzz
  - openssl
  run:
  - openconsole

about:
  license_file: LICENSE.md
  summary: A GPU-accelerated cross-platform terminal emulator and multiplexer
