context:
  version: 20231026
  sha256: fa75120560563a311241c05882016978bd35612692c7f0d39815a27837bff27d

package:
  name: aria2-toolchain
  version: 1.0.0

source:
- url: https://mirrors.cernet.edu.cn/msys2/distrib/x86_64/msys2-base-x86_64-{{ version }}.tar.xz
  sha256: '{{ sha256 }}'

build:
  include_recipe: false
  number: 1
  script_env:
    MSYSTEM: UCRT64
  skip:
  - not win64
  - build_platform != target_platform

requirements:
  run_constrained:
  - git <0a0
  - msys2-conda-epoch <0a0

test:
  commands:
  - bash --version

about:
  summary: Tools and libraries to build aria2 for native Windows
