context:
  version: 20240507
  sha256: 4625c9aaf9850da22dafa2a0a164de9143c7b9ee22fcb338b81a9f571f472a97

package:
  name: aria2-toolchain
  version: 1.0.0

source:
- url: https://mirrors.ustc.edu.cn/msys2/distrib/x86_64/msys2-base-x86_64-${{ version }}.tar.xz
  sha256: ${{ sha256 }}

build:
  number: 2
  skip:
  - not win
  - build_platform != target_platform

requirements:
  run_constraints:
  - git <0a0
  - msys2-conda-epoch <0a0

tests:
- script:
  - bash --version

about:
  summary: Tools and libraries to build aria2 for native Windows
