package:
  name: aria2-toolchain
  version: 1.0.0

source:
- url: https://mirrors.cernet.edu.cn/msys2/distrib/x86_64/msys2-base-x86_64-20230718.tar.xz
  sha256: 7d69011724f74e33d6080fe5fb1034fd63aeb00f8fc2414ca84628ef58493284
  folder: msys64
- path: scripts
  folder: scripts

build:
  include_recipe: false
  number: 0
  script_env:
    MSYSTEM: UCRT64
  skip:
  - not win64
  - build_platform != target_platform

test:
  commands:
  - bash --version

about:
  summary: Tools and libraries to build aria2 for native Windows
