context:
  version: 1.95.3
  version_full: ${{ version }}.24321
  sha256: daf0939e282355ef146bbde5e7cee6d0c91f746226303f7a6aaebfb06539e13c
  node_version: 20.18

package:
  name: vscodium-server
  version: ${{ version }}

source:
  url: https://github.com/VSCodium/VSCodium/releases/download/${{ version_full }}/vscodium-reh-web-win32-x64-${{ version_full }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: vscodium-server

build:
  number: 1
  skip:
  - not win

requirements:
  host:
  - m2-coreutils
  run:
  - nodejs ${{ node_version }}.*

tests:
- script:
  - code-server --version

about:
  license: MIT
  license_family: MIT
  summary: binary releases of VS Code without MS branding/telemetry/licensing
