context:
  license: GPL-3.0-or-later
  version: 0.230.0
  sha256: 69390981c840c909319614800fafca761d81807391659a28762a27ccecd19396

package:
  name: zed
  version: ${{ version }}

source:
- url: https://codeload.github.com/zed-industries/zed/tar.gz/v${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch
- url: https://github.com/zed-industries/livekit-rust-sdks/releases/download/webrtc-0001d84-4/webrtc-win-x64-release.zip
  sha256: b16f68e1fef8bd8089b9c7fc46c3c9b43ad5257c84460794a3668ec5accc1f13
  target_directory: webrtc

build:
  number: 0
  script:
    content:
    - set AWS_LC_SYS_PREBUILT_NASM=0
    - set "LK_CUSTOM_WEBRTC=%SRC_DIR%\webrtc"
    - cargo fetch
    - cargo install --frozen --no-default-features --no-track --path crates\zed --root "%LIBRARY_PREFIX%"
    env:
      ZED_UPDATE_EXPLANATION: Please use your package manager to update zed from conda-forge
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - cmake >=3.12.0
  - ${{ compiler('c') }}
  - nasm
  - rust >=1.93.0
  host:
  - icu 78.*
  run:
  - openconsole ==1.23.13503

tests:
- script:
  - zed --system-specs

about:
  license: ${{ license }}
  license_family: GPL
  license_file: LICENSE-GPL
  summary: Code at the speed of thought
