context:
  license: GPL-3.0-or-later
  version: 0.227.1
  sha256: 15f22913fa15aa7c7d2e6b386925856b70a679b709b9df485294c615d924eab7

package:
  name: zed
  version: ${{ version }}

source:
- url: https://codeload.github.com/zed-industries/zed/tar.gz/v${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch
- url: https://github.com/livekit/rust-sdks/releases/download/webrtc-0001d84-2/webrtc-win-x64-release.zip
  sha256: 16ebb2f7dc15db943313bd80b81bbd9689fa4cbf4bf65f3c407a93cc33d8afe8
  target_directory: webrtc

build:
  number: 0
  script:
    content:
    - set "LK_CUSTOM_WEBRTC=%SRC_DIR%\webrtc"
    - cargo fetch
    - cargo install --frozen --no-default-features --no-track --path crates\zed --root "%LIBRARY_PREFIX%"
    env:
      ZED_UPDATE_EXPLANATION: Please use your package manager to update zed from conda-forge
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - cmake >=3.12.0
  - ${{ compiler('c') }}
  - rust >=1.93.0
  host:
  - icu 78.*
  run:
  - openconsole ==1.23.13503

about:
  license: ${{ license }}
  license_family: GPL
  license_file: LICENSE-GPL
  summary: Code at the speed of thought
