[project]
name = 'feedstocks'
channels = ['conda-forge']
platforms = ['linux-64', 'win-64']
authors = ['snekdesign']
license-file = 'LICENSE'
readme = 'README.md'
repository = 'https://github.com/snekdesign/feedstocks'

[dependencies]
git = '>=2.47.0'
rattler-build = '>=0.25.0'

[tasks.build]
cmd = [
    'rattler-build',
    'build',
    '--no-include-recipe',
    '--variant-config', 'variants.yaml',
    '--recipe-dir',
]

[target.win-64.tasks.install]
cmd = 'localVSlayout/vs_BuildTools.exe --noweb'
depends-on = ['layout']

[target.win-64.tasks.layout]
cmd = [
    './vs_BuildTools.exe',
    '--layout', 'localVSlayout',
    '--add', 'Microsoft.VisualStudio.Component.VC.CLI.Support',
    '--add', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
    '--add', 'Microsoft.VisualStudio.Component.Windows11SDK.26100',
    '--lang', 'en-US',
]
depends-on = ['bootstrapper']
inputs = ['vs_BuildTools.exe']
outputs = ['localVSlayout/vs_BuildTools.exe']

[environments.bootstrapper]
features = ['bootstrapper']
no-default-feature = true

[feature.bootstrapper]
platforms = ['win-64']

[feature.bootstrapper.dependencies]
python = '>=3.10.0'
pyyaml = '*'

[feature.bootstrapper.tasks.bootstrapper]
cmd = 'rm -rf vs_BuildTools.exe; python -I get_msvc.py'
inputs = ['get_msvc.py', 'variants.yaml']
outputs = ['vs_BuildTools.exe']
