[project]
name = 'feedstocks'
channels = ['conda-forge']
platforms = ['linux-64', 'win-64']
authors = ['snekdesign']
license-file = 'LICENSE'
readme = 'README.md'
repository = 'https://github.com/snekdesign/feedstocks'

[dependencies]
git = '>=2.45.2'
rattler-build = '>=0.17.1'

[tasks.build]
cmd = [
    'rattler-build',
    'build',
    '--no-include-recipe',
    '--variant-config', 'variants.yaml',
    '--recipe-dir',
]

[target.win-64.tasks.msvc]
# Assume there is a global installation
cmd = [
    'pwsh',
    '-NoProfile',
    'Get-MSVC.ps1',
]
