[project]
name = 'feedstocks'
channels = ['conda-forge']
platforms = ['linux-64', 'osx-64', 'win-64']

authors = ['snekdesign']
license-file = 'LICENSE'
readme = 'README.md'
repository = 'https://github.com/snekdesign/feedstocks'

[dependencies]
rattler-build = '>=0.46.0'

[tasks.build]
cmd = [
    'rattler-build',
    'build',
    '--config-file', '$PIXI_HOME/config.toml',
    '--no-include-recipe',
    '--variant-config', 'variants.yaml',
    '--recipe-dir',
]

[tasks.build.env]
PIXI_HOME = '~/.pixi'

[tasks.debug]
cmd = [
    'rattler-build',
    'debug',
    '--config-file', '$PIXI_HOME/config.toml',
    '--recipe',
]

[tasks.debug.env]
PIXI_HOME = '~/.pixi'
