[project]
name = 'feedstocks'
channels = ['conda-forge']
platforms = ['win-64']

authors = ['snekdesign']
license-file = 'LICENSE'
readme = 'README.md'
repository = 'https://github.com/snekdesign/feedstocks'

[dependencies]
rattler-build = '>=0.32.1'

[target.win-64.dependencies]
m2-patch = '*'

[tasks.build]
cmd = [
    'rattler-build',
    'build',
    '--no-include-recipe',
    '--variant-config', 'variants.yaml',
    '--recipe-dir',
]

[environments.boa-build]
features = ['boa-build']
no-default-feature = true

[feature.boa-build]
platforms = ['win-64']

[feature.boa-build.dependencies]
boa = '>=0.17.0'

[feature.boa-build.tasks.boa-build]
cmd = ['boa', 'build', '--pkg-format=2']
