context:
  version: 1.37.0
  sha256: 60a420ad7085eb616cb6e2bdf0a7206d68ff3d37fb5a956dc44242eb2f79b66b
  sqlite_version: 3.46.0

package:
  name: aria2
  version: ${{ version }}

source:
- url: https://mirrors.sdu.edu.cn/github-release/aria2_aria2/release-${{ version }}/aria2-${{ version }}.tar.xz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch
- url: https://mirrors.cernet.edu.cn/msys2/mingw/ucrt64/mingw-w64-ucrt-x86_64-gettext-tools-0.22.5-2-any.pkg.tar.zst
  sha256: d46fccf7423bc4df9d89f3d4a14d11347c79f8058c10f2d1f5bfd9a11ba74f89

build:
  number: 1
  script:
    env:
      MSYS2_PATH_TYPE: inherit
      SQLITE_VERSION: ${{ sqlite_version }}
  skip:
  - not win
  - build_platform != target_platform
  - compiler('cxx')[:4] == 'vs20'

requirements:
  build:
  - ${{ compiler('cxx') }}
  - m2-autoconf
  - m2-automake-wrapper
  - m2-findutils
  - m2-gettext
  - m2-grep
  - m2-libtool
  - m2-make
  - m2-pkg-config
  - m2-which
  host:
  - c-ares
  - libintl-devel
  - libsqlite ${{ sqlite_version }}
  - libssh2
  - libxml2
  - openssl
  - xz
  - zlib
  ignore_run_exports:
    from_package:
    - xz

tests:
- script:
  - aria2c -v

about:
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: aria2 is a lightweight multi-protocol & multi-source, cross platform download utility operated in command-line. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink.
