context:
  version: 1.37.0
  sha256: 60a420ad7085eb616cb6e2bdf0a7206d68ff3d37fb5a956dc44242eb2f79b66b
  sqlite_version: 3.49.1

package:
  name: aria2
  version: ${{ version }}

source:
- url: https://github.com/aria2/aria2/releases/download/release-${{ version }}/aria2-${{ version }}.tar.xz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch
- url: https://mirror.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-gettext-tools-0.24-2-any.pkg.tar.zst
  sha256: 969b57acfe0d612ee2eae501b0cc13719a6b59822a4aff6d9e58e335c69d3e2d

build:
  number: 3
  script:
    env:
      MSYS2_PATH_TYPE: inherit
      SQLITE_VERSION: ${{ sqlite_version }}
  skip:
  - not win
  - build_platform != target_platform
  - compiler('cxx')[:2] == 'vs'

requirements:
  build:
  - ${{ compiler('cxx') }}
  - m2-autoconf
  - m2-automake-wrapper
  - m2-base
  - m2-libtool
  - m2-make
  - m2-pkg-config
  host:
  - c-ares
  - libintl-devel
  - libsqlite ==${{ sqlite_version }}
  - libssh2
  - libxml2
  - openssl
  - xz-tools
  - zlib

tests:
- script:
  - aria2c -v

about:
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: aria2 is a lightweight multi-protocol & multi-source, cross platform download utility operated in command-line. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink.
