context:
  version: 1.37.0
  sha256: 9104878396cc30441976afdd3af9331ec51306fabf92fb82724c3b8fa7d72932

package:
  name: aria2
  version: ${{ version }}

source:
- url: https://github.com/aria2/aria2/archive/refs/tags/release-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch

build:
  number: 1
  skip:
  - not win
  - build_platform != target_platform

requirements:
  host:
  - aria2-toolchain
  - c-ares
  - libintl-devel
  - libsqlite
  - libssh2
  - libxml2
  - openssl
  - zlib

tests:
- script:
  - aria2c -v

about:
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: aria2 is a lightweight multi-protocol & multi-source, cross platform download utility operated in command-line. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink.
