context:
  major: 25
  minor: 0
  version: ${{ major }}.${{ minor }}.0
  version_string: ${{ major }}0${{ minor }}
  sha256_src: bff9e69b6ca73a5b8715d7623870a39dc90ad6ce1f4d1070685843987af1af9b
  sha256_linux64: 15e914b5452f1da7879c6e12868d389fde5111cafab87b34857a2e3a12018409

package:
  name: 7zz
  version: ${{ version }}

source:
- if: win
  then:
  - url: https://7-zip.org/a/7z${{ version_string }}-src.tar.xz
    sha256: ${{ sha256_src }}
    patches:
    - 0001-always-o2.patch
    - 0002-7max.patch
  else:
  - url: https://7-zip.org/a/7z${{ version_string }}-linux-x64.tar.xz
    sha256: ${{ sha256_linux64 }}

build:
  number: 0
  skip:
  - not (win or linux)
  - build_platform != target_platform
  - win and not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - if: win
    then: ${{ compiler('cxx') }}
  run_constraints:
  - 7zip <0a0

tests:
- script:
  - 7zz

about:
  license_file: License.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
