context:
  major: 25
  minor: 1
  version: ${{ major }}.${{ minor }}.0
  version_string: ${{ major }}0${{ minor }}
  sha256_src: ed087f83ee789c1ea5f39c464c55a5c9d4008deb0efe900814f2df262b82c36e
  sha256_linux64: 4ca3b7c6f2f67866b92622818b58233dc70367be2f36b498eb0bdeaaa44b53f4

package:
  name: 7zz
  version: ${{ version }}

source:
- if: win
  then:
  - url: https://7-zip.org/a/7z${{ version_string }}-src.tar.xz
    sha256: ${{ sha256_src }}
    patches:
    - 0001-always-o2.patch
    - 0002-7max.patch
  else:
  - url: https://7-zip.org/a/7z${{ version_string }}-linux-x64.tar.xz
    sha256: ${{ sha256_linux64 }}

build:
  number: 0
  script:
  - if: win
    then:
    - mklink /H License.txt DOC\License.txt
    - cd CPP\7zip\Bundles\Alone2
    - nmake MY_DYNAMIC_LINK=1 PLATFORM=x64
    - mklink /H "%LIBRARY_BIN%\7zz.exe" x64\7zz.exe
    - cd ..\SFXWin
    - nmake PLATFORM=x64
    - mklink /H "%LIBRARY_BIN%\7z.sfx" x64\7z.sfx
    else:
    - mkdir -p "$PREFIX/bin"
    - ln 7zz "$PREFIX/bin"
  skip:
  - not (win or linux)
  - build_platform != target_platform
  - win and not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - if: win
    then: ${{ compiler('cxx') }}
  run_constraints:
  - 7zip <0a0

tests:
- script:
  - 7zz

about:
  license_file: License.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
