context:
  major: 24
  minor: 6
  version: ${{ major }}.${{ minor }}.0
  version_string: ${{ major }}0${{ minor }}
  sha256_src: 2aa1660c773525b2ed84d6cd7ff0680c786ec0893b87e4db44654dcb7f5ac8b5
  sha256_linux64: 807bd858433b13215abc915cbb9ccdc806fc7b421418a4088a194e1729a6a6b2

package:
  name: 7zz
  version: ${{ version }}

source:
- if: win
  then:
  - url: https://mirror.nju.edu.cn/7-zip/7z${{ version_string }}-src.tar.xz
    sha256: ${{ sha256_src }}
    patches:
    - 0001-always-o2.patch
  else:
  - url: https://mirror.nju.edu.cn/7-zip/7z${{ version_string }}-linux-x64.tar.xz
    sha256: ${{ sha256_linux64 }}

build:
  number: 0
  skip:
  - not (win or linux)
  - build_platform != target_platform

requirements:
  build:
  - if: win
    then: ${{ compiler('cxx') }}
  run_constraints:
  - 7zip <0a0

tests:
- script:
  - 7zz

about:
  license_file: License.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
