context:
  major: 24
  minor: 7
  version: ${{ major }}.${{ minor }}.0
  version_string: ${{ major }}0${{ minor }}
  sha256_src: d1b0874a3f1c26df21c761a4a30691dc1213e8577f18ee78326c14ca4d683e2b
  sha256_linux64: 4a47877a7f6eba7fe6c900f7379bb2061b9620b588cf3189d99ae2a8aaa8f503

package:
  name: 7zz
  version: ${{ version }}

source:
- if: win
  then:
  - url: https://mirror.nju.edu.cn/7-zip/7z${{ version_string }}-src.tar.xz
    sha256: ${{ sha256_src }}
    patches:
    - 0001-always-o2.patch
    - 0002-7max.patch
  else:
  - url: https://mirror.nju.edu.cn/7-zip/7z${{ version_string }}-linux-x64.tar.xz
    sha256: ${{ sha256_linux64 }}

build:
  number: 1
  skip:
  - not (win or linux)
  - build_platform != target_platform
  - win and compiler('cxx')[:3] == 'gxx'

requirements:
  build:
  - if: win
    then: ${{ compiler('cxx') }}
  run_constraints:
  - 7zip <0a0

tests:
- script:
  - 7zz

about:
  license_file: License.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
