context:
  major: 24
  minor: 9
  version: ${{ major }}.${{ minor }}.0
  version_string: ${{ major }}0${{ minor }}
  sha256_src: 49c05169f49572c1128453579af1632a952409ced028259381dac30726b6133a
  sha256_linux64: 914c7e20ad5ef8e4d3cf08620ff8894b28fe11b7eb99809d6930870fbe48a281

package:
  name: 7zz
  version: ${{ version }}

source:
- if: win
  then:
  - url: https://mirror.nju.edu.cn/7-zip/7z${{ version_string }}-src.tar.xz
    sha256: ${{ sha256_src }}
    patches:
    - 0001-always-o2.patch
    - 0002-7max.patch
  else:
  - url: https://mirror.nju.edu.cn/7-zip/7z${{ version_string }}-linux-x64.tar.xz
    sha256: ${{ sha256_linux64 }}

build:
  number: 0
  skip:
  - not (win or linux)
  - build_platform != target_platform
  - win and compiler('cxx')[:3] == 'gxx'

requirements:
  build:
  - if: win
    then: ${{ compiler('cxx') }}
  run_constraints:
  - 7zip <0a0

tests:
- script:
  - 7zz

about:
  license_file: License.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
