context:
  major: 24
  minor: 8
  version: ${{ major }}.${{ minor }}.0
  version_string: ${{ major }}0${{ minor }}
  sha256_src: aa04aac906a04df59e7301f4c69e9f48808e6c8ecae4eb697703a47bfb0ac042
  sha256_linux64: 9b3a2edf0644a2b00b0a39ab6843f426128e4a6f6f98c40f8c02a668e5b5b59b

package:
  name: 7zz
  version: ${{ version }}

source:
- if: win
  then:
  - url: https://mirror.nju.edu.cn/7-zip/7z${{ version_string }}-src.tar.xz
    sha256: ${{ sha256_src }}
    patches:
    - 0001-always-o2.patch
    - 0002-7max.patch
  else:
  - url: https://mirror.nju.edu.cn/7-zip/7z${{ version_string }}-linux-x64.tar.xz
    sha256: ${{ sha256_linux64 }}

build:
  number: 1
  skip:
  - not (win or linux)
  - build_platform != target_platform
  - win and compiler('cxx')[:3] == 'gxx'

requirements:
  build:
  - if: win
    then: ${{ compiler('cxx') }}
  run_constraints:
  - 7zip <0a0

tests:
- script:
  - 7zz

about:
  license_file: License.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
