context:
  version: '23.1'
  version_string: '{{ version|replace(".", "0"*(5-len(version))) }}'
  sha256_src: 356071007360e5a1824d9904993e8b2480b51b570e8c9faf7c0f58ebe4bf9f74
  sha256_linux64: 23babcab045b78016e443f862363e4ab63c77d75bc715c0b3463f6134cbcf318

package:
  name: 7zz
  version: '{{ version }}'

source:
- sel(win64):
    url: https://7-zip.org/a/7z{{ version_string }}-src.tar.xz
    sha256: '{{ sha256_src }}'
    patches:
    - 0001-always-o2.patch
- sel(linux64):
    url: https://7-zip.org/a/7z{{ version_string }}-linux-x64.tar.xz
    sha256: '{{ sha256_linux64 }}'

build:
  include_recipe: false
  number: 0
  skip:
  - not (win64 or linux64)
  - build_platform != target_platform

requirements:
  build:
  - sel(win64): "{{ compiler('c') }}"

test:
  commands:
  - 7zz

about:
  license_file:
  - sel(win64): DOC/License.txt
  - sel(linux64): License.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
