context:
  major: 24
  minor: 1
  version: ${{ major }}.${{ minor }}.0
  version_string: ${{ major }}0${{ minor }}
  sha256: 587b593a9987c92ae01bdf8909d2b8101c41ae08546887f74ed08150cddaef0b

package:
  name: 7max
  version: ${{ version }}

source:
  url: https://master.dl.sourceforge.net/project/sevenmax/7-max/${{ major }}.0${{ minor }}/7max${{ version_string }}-src.7z?viasf=1
  sha256: ${{ sha256 }}
  patches:
  - 0001-always-o2.patch

build:
  number: 1
  script:
  - mklink /H copying.txt DOC\copying.txt
  - cd CPP\Utils\7max\Console
  - nmake MY_DYNAMIC_LINK=1 PLATFORM=x64
  - mklink /H "%LIBRARY_BIN%\7maxc.exe" x64\7maxc.exe
  - cd ..\DLL
  - nmake MY_DYNAMIC_LINK=1 PLATFORM=x64
  - mklink /H "%LIBRARY_BIN%\7max.dll" x64\7max.dll
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - 7zip
  - ${{ compiler('cxx') }}

tests:
- script:
  - 7maxc

about:
  license_file: copying.txt
