context:
  version: 2.0.18
  sha256_src: 5be981d391fc6f88df0cf5673e5a9e313c794e87b2f0534634a1a9978872a55e
  sha256_bin: bf3a27398397b886a3d8b0ad2591c29a7165d1f560b1943a8bc120497b6ea5f8

package:
  name: autohotkey
  version: ${{ version }}

source:
- url: https://github.com/AutoHotkey/AutoHotkey/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256_src }}
  patches:
  - 0001-conda-build.patch
- url: https://github.com/AutoHotkey/AutoHotkey/releases/download/v${{ version }}/AutoHotkey_${{ version }}.zip
  sha256: ${{ sha256_bin }}
  target_directory: bin

build:
  number: 1
  skip:
  - not win
  - build_platform != target_platform
  - compiler('cxx')[:4] != 'vs20'

requirements:
  build:
  - ${{ compiler('cxx') }}
  host:
  - libmamba 2.*

about:
  license: GPL-2.0-only
  license_family: GPL
  license_file: license.txt
  summary: macro-creation and automation-oriented scripting utility for Windows
