context:
  version: 2.0.19
  sha256_src: 7813fc61f55a964a95220357e33dbc41f3bb18f12a58486bc6530cc2de115909
  sha256_bin: 4e0d0e65655066a646a210951320feaef0729a3597177131adaec4066bef5869

package:
  name: autohotkey
  version: ${{ version }}

source:
- url: https://codeload.github.com/AutoHotkey/AutoHotkey/tar.gz/v${{ version }}
  sha256: ${{ sha256_src }}
  patches:
  - 0001-conda-build.patch
- url: https://github.com/AutoHotkey/AutoHotkey/releases/download/v${{ version }}/AutoHotkey_${{ version }}.zip
  sha256: ${{ sha256_bin }}
  target_directory: bin

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('cxx') }}

about:
  license: GPL-2.0-only
  license_family: GPL
  license_file: license.txt
  summary: macro-creation and automation-oriented scripting utility for Windows
