context:
  version: 2.0.22
  sha256_src: 953cfc18c1c62848f6327941a969f5c3d816c8f90dd70008d0e1ba3b03d6fa92
  sha256_bin: 9cd93e5793404d8c2585b73f15be244872cc4deccf5fa8b6f1f7b2a549fbbfd4

package:
  name: autohotkey
  version: ${{ version }}

source:
- url: https://codeload.github.com/AutoHotkey/AutoHotkey/tar.gz/v${{ version }}
  sha256: ${{ sha256_src }}
  patches:
  - changes.patch
- url: https://github.com/AutoHotkey/AutoHotkey/releases/download/v${{ version }}/AutoHotkey_${{ version }}.zip
  sha256: ${{ sha256_bin }}
  target_directory: bin

build:
  number: 0
  script:
  - md "%LIBRARY_PREFIX%\share\autohotkey\inc"
  - msbuild AutoHotkeyx.vcxproj -p:Configuration=Release;Platform=x64
  - mklink /H "%LIBRARY_BIN%\AutoHotkey.exe" bin\AutoHotkey64.exe
  - mklink /H "%LIBRARY_PREFIX%\share\autohotkey\AutoHotkey.chm" bin\AutoHotkey.chm
  - mklink /H "%LIBRARY_PREFIX%\share\autohotkey\WindowSpy.ahk" bin\UX\WindowSpy.ahk
  - mklink /H "%LIBRARY_PREFIX%\share\autohotkey\inc\spy.ico" bin\UX\inc\spy.ico
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('cxx') }}

about:
  license: GPL-2.0-only
  license_family: GPL
  license_file: license.txt
  summary: macro-creation and automation-oriented scripting utility for Windows
