context:
  version: 1.1.0.30
  sha256: f8f78be9682b32941794510c05eb7b91211b5e5daf3e810d2a5e12b934373a81

package:
  name: everything-cli
  version: ${{ version }}

source:
  url: https://codeload.github.com/voidtools/ES/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch

build:
  number: 0
  script:
  - cd src
  - cl -DUNICODE -Fe"%LIBRARY_BIN%\es.exe" -GL -MD -O2 cli.c shlwapi.lib user32.lib
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}

tests:
- script:
  - es -version

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Everything Command Line Interface
