context:
  version: 1.1.0.33
  sha256: a4a0e08aa17fff51c655652fbe7ca5a08a0dc52efc9991f030e898e6c8e133a2

package:
  name: everything-cli
  version: ${{ version }}

source:
  url: https://codeload.github.com/voidtools/ES/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
  - cd vs2019
  - msbuild -p:Configuration=Release;Platform=x64
  - mklink /H "%LIBRARY_BIN%\es.exe" x64\Release\es.exe
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}

tests:
- script:
  - es -version

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Everything Command Line Interface
