context:
  version: 1.1.0.34
  sha256: 1a77f3ed16209edd476dd2cecc123d1ab0de94fbe9ae9d2878fa59941f18f6d3

package:
  name: everything-cli
  version: ${{ version }}

source:
  url: https://codeload.github.com/voidtools/ES/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
  - cd vs2019
  - msbuild -p:Configuration=Release;Platform=x64
  - mklink /H "%LIBRARY_BIN%\es.exe" x64\Release\es.exe
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}

tests:
- script:
  - es -version

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Everything Command Line Interface
