context:
  version: 1.1.0.30
  sha256: f8f78be9682b32941794510c05eb7b91211b5e5daf3e810d2a5e12b934373a81

package:
  name: everything-cli
  version: ${{ version }}

source:
  url: https://github.com/voidtools/ES/archive/refs/tags/${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - changes.patch

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}

tests:
- script:
  - es -version

about:
  license: MIT
