context:
  version: 1.1.0.38
  sha256: 013f19e44c0f26cdb0a6f81d9dc4c0cdc6aa099f1379900ac966a4f74bd26dd5

package:
  name: everything-cli
  version: ${{ version }}

source:
  url: https://codeload.github.com/voidtools/ES/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch

build:
  number: 0
  script:
  - cd vs2019
  - msbuild -p:Configuration=Release;Platform=x64
  - mklink /H "%LIBRARY_BIN%\es.exe" x64\Release\es.exe
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}

tests:
- script:
  - es -version

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Everything Command Line Interface
