context:
  version: 1.1.0.36
  sha256: 1b2bd8e339173143cd8e6f8e6463375ddf49ac4bf1d7ee30aa044724a8af06ed

package:
  name: everything-cli
  version: ${{ version }}

source:
  url: https://codeload.github.com/voidtools/ES/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
  - cd vs2019
  - msbuild -p:Configuration=Release;Platform=x64
  - mklink /H "%LIBRARY_BIN%\es.exe" x64\Release\es.exe
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}

tests:
- script:
  - es -version

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Everything Command Line Interface
