context:
  version: 3.0.1

package:
  name: klaus-full
  version: ${{ version }}

build:
  number: 0
  script:
  - copy "%RECIPE_DIR%\klaus.cmd" "%LIBRARY_BIN%"
  - copy "%RECIPE_DIR%\_klaus_full.py" "%SP_DIR%"
  skip:
  - not win

requirements:
  host:
  - python
  run:
  - dulwich <=0.23.0
  - git
  - gitoxide
  - granian
  - klaus ==${{ version }}
  - python >=3.10.0

tests:
- script:
  - klaus --version
