context:
  version: 3.0.1

package:
  name: klaus-full
  version: ${{ version }}

build:
  number: 0
  skip:
  - not win

requirements:
  host:
  - python
  run:
  - dulwich <=0.23.0
  - git
  - gitoxide
  - granian
  - klaus ==${{ version }}
  - python >=3.10.0

tests:
- script:
  - klaus --version
