context:
  # curl https://open-vsx.org/api/detachhead/basedpyright/versions?size=1
  version: 1.37.3
  # curl -L https://open-vsx.org/api/detachhead/basedpyright/latest/file/sha256
  sha256: d939aabb9883977851d756d176e3d6fb084e63e31a29b07e6af07f2b77224380

package:
  name: vscode-pyright
  version: ${{ version }}

source:
  url: https://open-vsx.org/api/detachhead/basedpyright/${{ version }}/file/detachhead.basedpyright-${{ version }}.vsix
  sha256: ${{ sha256 }}

build:
  number: 0
  script:
  - md "%LIBRARY_PREFIX%\opt\vscodium\bootstrap\extensions"
  - mklink /H "%LIBRARY_PREFIX%\opt\vscodium\bootstrap\extensions\detachhead.basedpyright-${{ version }}.vsix" detachhead.basedpyright-${{ version }}.vsix
  skip:
  - not win
  - build_platform != target_platform

requirements:
  run:
  - vscodium >=1.103.15539
  run_constraints:
  - ty-vscode <0a0

about:
  license: MIT
  license_family: MIT
  summary: VS Code static type checking for Python (but based)
