context:
  name: streamlit
  version: 1.41.1
  sha256: 6626d32b098ba1458b71eebdd634c62af2dd876380e59c4b6a1e828a39d62d69

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[:1] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch

build:
  noarch: python
  number: 0
  python:
    entry_points:
    - streamlit = streamlit.web.cli:main
  script: pip install .

requirements:
  host:
  - pip
  - python >=3.9.8
  - setuptools
  - wheel
  run:
  - altair >=4.0,<6
  - blinker >=1.0.0,<2
  - cachetools >=4.0,<6
  - click >=7.0,<9
  - gitpython >=3.0.7,<4,!=3.1.19
  - numpy >=1.23,<3
  - packaging >=20,<25
  - pandas >=1.4.0,<3
  - pillow >=7.1.0,<12
  - protobuf >=3.20,<6
  - pyarrow >=7.0
  - pydeck >=0.8.0b4,<1
  - python >=3.9.8
  - python-dateutil >=2.7.3,<3
  - requests >=2.27,<3
  - rich >=10.14.0,<14
  - tenacity >=8.1.0,<10
  - toml >=0.10.1,<2
  - tornado >=6.0.3,<7
  - typing_extensions >=4.3.0,<5
  - tzlocal >=1.1,<6
  - watchdog >=2.1.5,<7

tests:
- script:
  - streamlit --version

about:
  homepage: https://streamlit.io
  summary: A faster way to build and share data apps
  license: Apache-2.0
