context:
  version: 0.40.0
  sha256: 9da7dd6d0c86ca5fc0eb06768a9edaf7288a54c936f2d20f7923fcaf705e96db

package:
  name: rattler-build
  version: ${{ version }}

source:
  url: https://github.com/prefix-dev/rattler-build/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch

build:
  number: 0
  script:
  - if: win
    then:
    - cargo install --bin rattler-build --no-track --path . --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --bin rattler-build --no-track --path . --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust ==1.83.0
  - if: linux
    then: diffutils
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  run:
  - if: linux
    then: patchelf

tests:
- script:
  - rattler-build -V

about:
  license_file: LICENSE
  summary: rattler-build is the universal conda package builder for Windows, macOS and Linux
