context:
  version: 0.35.6
  sha256: c978c372d25fc29c922e7af82deb15337bc3961721ca3fb5da3804f460a4b02e

package:
  name: rattler-build
  version: ${{ version }}

source:
- url: https://github.com/prefix-dev/rattler-build/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch
- url: https://github.com/wolfv/zip2/archive/refs/heads/patched.tar.gz
  sha256: a9d60c40aaa017c462830aeb7867d8f4c17099f6e5504577f8229668b51d0bd1
  target_directory: zip2

build:
  number: 0
  script:
  - cargo build --release
  - if: win
    then:
    - mklink /H "%LIBRARY_BIN%\rattler-build.exe" target\release\rattler-build.exe
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust ==1.83.0

tests:
- script:
  - rattler-build -V

about:
  license_file: LICENSE
  summary: rattler-build is the universal conda package builder for Windows, macOS and Linux
