context:
  version: 0.39.0
  sha256: 6625a0175d62d0b3cc957e683e9de4258a413db6e6a7a613be86cc15a495c2cf

package:
  name: rattler-build
  version: ${{ version }}

source:
- url: https://github.com/prefix-dev/rattler-build/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch
- url: https://github.com/wolfv/zip2/archive/refs/heads/patched.tar.gz
  sha256: 0d2510a4cab7d8ce826a5122ccf614d1e5955d1a4349c37e6d5f7dd2942adf8b
  target_directory: zip2

build:
  number: 0
  script:
  - if: win
    then:
    - cargo install --no-track --path . --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --no-track --path . --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust ==1.83.0
  - if: linux
    then: diffutils
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}

tests:
- script:
  - rattler-build -V

about:
  license_file: LICENSE
  summary: rattler-build is the universal conda package builder for Windows, macOS and Linux
