context:
  version: 0.4.0
  sha256: 175aca3adcffb951ef4f4e670fce764db9e86cc062620cbd69708c4e76562e31

package:
  name: servo
  version: ${{ version }}

source:
- url: https://codeload.github.com/servo/servo/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch
- url: https://codeload.github.com/KyleMayes/clang-sys/tar.gz/v1.8.1
  sha256: f3571b3033fc6ff32f86326de724ece3ced7867f2016ccf7cdb36284d3f9c9b8
  target_directory: clang-sys
  patches:
  - 0001-conda-build.patch
# https://book.servo.org/building/building-offline.html#prebuilt-spidermonkey-artifacts
- url: https://github.com/servo/mozjs/releases/download/mozjs-sys-v140.12.0-2/libmozjs-x86_64-pc-windows-msvc.tar.gz
  sha256: 1928f554601c43cfc794a4cb3996aeab8447869a2a17a75b0e3487f16e72558d
  file_name: libmozjs.tar.gz

build:
  number: 0
  script: build.py
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('cxx') }}
  - libclang13
  - nasm
  - pkg-config
  - python >=3.14.0
  - rust >=1.86.0
  host:
  - glib
  - gst-libav >=1.18.0
  - gst-plugins-bad >=1.18.0
  - gst-plugins-base >=1.18.0
  - gst-plugins-good >=1.18.0
  - gstreamer >=1.18.0
  - m2-coreutils
  - zlib

tests:
- script:
  - servo -V

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: Servo aims to empower developers with a lightweight, high-performance alternative for embedding web technologies in applications.
