context:
  version: 0.6.0
  sha256: 9f4b0223d5d6f2f327a4628fc69dd53ffffe2d8928e7f9623d066d528980baf8

package:
  name: servo
  version: ${{ version }}

source:
- url: https://codeload.github.com/servo/servo/tar.gz/v${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch
# https://book.servo.org/building/building-offline.html#prebuilt-spidermonkey-artifacts
- url: https://github.com/servo/mozjs/releases/download/mozjs-sys-v153.3.0-3/libmozjs-x86_64-pc-windows-msvc.tar.gz
  sha256: 4668c61b92b178b65f555d3eb36652f16681bfeedbd1e2f41e063d4a78caace1
  file_name: libmozjs.tar.gz

build:
  number: 0
  script:
    file: build.py
    env:
      CARGO_HOME: ${{ env.get('CARGO_HOME', default='') }}
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('cxx') }}
  - libclang >=23.1.0
  - nasm
  - pkg-config
  - python >=3.14.0
  - rust >=1.86.0
  host:
  - glib
  - gst-libav >=1.18.0
  - gst-plugins-bad >=1.18.0
  - gst-plugins-base >=1.18.0
  - gst-plugins-good >=1.18.0
  - gstreamer >=1.18.0
  - m2-coreutils
  - zlib

tests:
- script:
  - servo -V

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: Servo aims to empower developers with a lightweight, high-performance alternative for embedding web technologies in applications.
