context:
  version: 1.0.0.14
  sha256: 6e978fad04f0f070aac509fd116a51fead6d4885181931837c723b82bd9c3e67

package:
  name: voidimageviewer
  version: ${{ version }}

source:
- url: https://codeload.github.com/voidtools/voidImageViewer/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch
- path: CMakeLists.txt

build:
  number: 0
  script:
  - cmake -B build
  - cmake --build build --config Release
  - cmake --install build --prefix "%LIBRARY_PREFIX%"
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - cmake >=4.0.0
  - ${{ compiler('c') }}
  host:
  - libwebp-base >=1.3.2

about:
  license_file: LICENSE
  summary: Lightweight image viewer for Windows with animated GIF/WEBP support
