context:
  version: 0.4.16
  sha256: 978d2f7770cda793df05929f01e5ea2ff4939140982fa1a5bdb4e12c941e91d9

recipe:
  name: libcmd
  version: ${{ version }}

source:
- url: https://codeload.github.com/reactos/reactos/tar.gz/0.4.16-release
  sha256: ${{ sha256 }}
  patches:
  - 0001-cmd.dll.patch
- path: libcmd.def
  target_directory: base/shell/cmd

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

outputs:
- staging:
    name: libcmd-build
  requirements:
    build:
    - cmake >=3.17.0,<4
    - ${{ compiler('cxx') }}
    - ninja
    - winflexbison
  build:
    script:
    - call configure.cmd %CMAKE_ARGS%
    - cd output-VS-amd64
    - ninja base\shell\cmd\cmd.dll
    - cd base\shell\cmd
    - mklink /H "%LIBRARY_BIN%\cmd.dll" cmd.dll
    - md "%LIBRARY_INC%" "%LIBRARY_LIB%"
    - mklink /H "%LIBRARY_LIB%\cmd.lib" cmd.lib
    - copy "%RECIPE_DIR%\cmd.h" "%LIBRARY_INC%"
- package:
    name: libcmd
  inherit: libcmd-build
  build:
    files:
    - Library/bin/cmd.dll
- package:
    name: libcmd-devel
  inherit: libcmd-build
  requirements:
    run:
    - ${{ pin_subpackage('libcmd', exact=True) }}
    run_exports:
    - ${{ pin_subpackage('libcmd', exact=True) }}
  build:
    files:
    - Library/include/cmd.h
    - Library/lib/cmd.lib

about:
  license_file:
  - COPYING
  - base/shell/cmd/license.txt
