context:
  version: 0.4.15
  sha256: 317a1d17798c45d5e81facd0f910aa6f1457826c4cc359fed8011d116f194043

recipe:
  name: libcmd
  version: ${{ version }}

build:
  number: 0
  script:
  - if exist "%LIBRARY_BIN%\cmd.dll" ( exit 0 )
  - call configure.cmd %CMAKE_ARGS%
  - cd output-VS-amd64
  - ninja base\shell\cmd\cmd.dll
  - cd base\shell\cmd
  - mklink /H "%LIBRARY_BIN%\cmd.dll" cmd.dll
  - md "%LIBRARY_INC%" "%LIBRARY_LIB%"
  - mklink /H "%LIBRARY_LIB%\cmd.lib" cmd.lib
  - copy "%RECIPE_DIR%\cmd.h" "%LIBRARY_INC%"
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

cache:
  source:
    url: https://codeload.github.com/reactos/reactos/tar.gz/${{ version }}-release
    sha256: ${{ sha256 }}
    patches:
    - 0001-cmd.dll.patch
  requirements:
    build:
    - cmake >=3.17.0,<4
    - ${{ compiler('cxx') }}
    - ninja
    - winflexbison

outputs:
- package:
    name: libcmd
  build:
    files:
    - Library/bin/cmd.dll
- package:
    name: libcmd-devel
  requirements:
    run:
    - ${{ pin_subpackage('libcmd', exact=True) }}
    run_exports:
    - ${{ pin_subpackage('libcmd', exact=True) }}
  build:
    files:
    - Library/include/cmd.h
    - Library/lib/cmd.lib

about:
  license_file:
  - COPYING
  - base/shell/cmd/license.txt
