context:
  version: 1.22.10731
  sha256: 06bb5c28956ca16f4cbbe00573e890ed3cade1400d599755ffe399566208d886

package:
  name: openconsole
  version: ${{ version }}

source:
- url: https://github.com/microsoft/terminal/archive/refs/tags/v${{ version }}.0.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch
# ms-gsl 3.1.0 is missing in conda-forge; added as source
- url: https://github.com/microsoft/GSL/archive/refs/tags/v3.1.0.tar.gz
  sha256: d3234d7f94cea4389e3ca70619b82e8fb4c2f33bb3a070799f1e18eef500a083
  target_directory: dep/gsl

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - compiler('cxx')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('cxx') }}
  host:
  - fmt
  - icu 75.*
  - mingw-w64-ucrt-x86_64-crt-git
  - wil

about:
  license_file: LICENSE
