context:
  version: 1.21.2911
  version_gsl: 0f6dbc9e2915ef5c16830f3fa3565738de2a9230
  version_wil: 1.0.240122.1
  sha256: 97b5295186156fdfe849539eb63142b13fde561e24eebfecac33100cde1af254
  sha256_gsl: c6dc53a876c2f079b711e33be5ff7809525872c3f6a086af91d061dae5665686
  sha256_wil: 2762643e7865c42ac60d809fe951a813ae10960141e56bb74ad28843f2d6b5c1

package:
  name: openconsole
  version: ${{ version }}

source:
- url: https://github.com/microsoft/terminal/archive/refs/tags/v${{ version }}.0.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch
- url: https://github.com/microsoft/GSL/archive/${{ version_gsl }}.tar.gz
  sha256: ${{ sha256_gsl }}
  target_directory: dep/gsl
- url: https://globalcdn.nuget.org/packages/microsoft.windows.implementationlibrary.${{ version_wil }}.nupkg
  sha256: ${{ sha256_wil }}

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - compiler('cxx')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('cxx') }}
  host:
  - 7zip
  - mingw-w64-ucrt-x86_64-crt-git

about:
  license_file: LICENSE
