context:
  version: 3.5.2
  sha256: d97e7135fa6c90d2dca9937d3234a8650391035f0a0203b670709334e5398204

package:
  name: sumatrapdf
  version: ${{ version }}

source:
  url: https://github.com/sumatrapdfreader/sumatrapdf/archive/refs/tags/${{ version }}rel.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 1
  skip:
  - not win
  - build_platform != target_platform
  - compiler('cxx')[:4] != 'vs20'

requirements:
  build:
  - ${{ compiler('cxx') }}
  host:
  - harfbuzz
  - libgumbo
  - libheif
  - libunrar
  - libwebp-base
  - m2-sed
  - openjpeg
  - zlib

about:
  license_file: AUTHORS
  summary: SumatraPDF reader
