context:
  version: 3.6.0
  sha256: 831aec4f5a54e2a2dda7ee842413aa117e1f240bcd3310799aa2cf26264f1293

package:
  name: sumatrapdf
  version: ${{ version }}

source:
  url: https://codeload.github.com/sumatrapdfreader/sumatrapdf/tar.gz/${{ version|trim('0')|trim('.') }}rel
  sha256: ${{ sha256 }}
  patches:
  - changes.patch

build:
  number: 0
  script:
  - msbuild vs2022\SumatraPDF.vcxproj -p:Configuration=Release;Platform=x64
  - mklink /H "%LIBRARY_BIN%\SumatraPDF.exe" out\rel64\SumatraPDF.exe
  - (robocopy "%RECIPE_DIR%" "%LIBRARY_PREFIX%\etc\sumatrapdf" settings.txt) ^& if %ERRORLEVEL% LEQ 1 exit 0
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('cxx') }}
  host:
  - bzip2
  - freetype
  - harfbuzz
  - jbig2dec
  - libbrotlidec
  - libbrotlienc
  - libgumbo
  - libheif
  - libjpeg-turbo
  - libunrar
  - libwebp-base
  - openjpeg
  - zlib
  ignore_run_exports:
    from_package:
    - jbig2dec

about:
  license_file: AUTHORS
  summary: SumatraPDF reader
