context:
  version: 3.5.2
  sha256: d97e7135fa6c90d2dca9937d3234a8650391035f0a0203b670709334e5398204

package:
  name: sumatrapdf
  version: ${{ version }}

source:
  url: https://codeload.github.com/sumatrapdfreader/sumatrapdf/tar.gz/${{ version }}rel
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 1
  script:
  - cd vs2022
  - sed -i "s MultiThreaded< MultiThreadedDLL< " bin2coff.vcxproj chm.vcxproj enginedump.vcxproj engines.vcxproj libdjvu.vcxproj libmupdf.vcxproj logview.vcxproj MakeLZSA.vcxproj mupdf-libs.vcxproj mupdf.vcxproj PdfFilter.vcxproj PdfPreview.vcxproj PdfPreviewTest.vcxproj plugin-test.vcxproj signfile.vcxproj sizer.vcxproj SumatraPDF.vcxproj SumatraPDF-dll.vcxproj test_util.vcxproj unarrlib.vcxproj utils.vcxproj
  - cd ..
  - msbuild vs2022\SumatraPDF.vcxproj -p:Configuration=Release;Platform=x64
  - mklink /H "%LIBRARY_BIN%\SumatraPDF.exe" out\rel64\SumatraPDF.exe
  - mklink /H "%LIBRARY_PREFIX%\etc\SumatraPDF-settings.txt" "%RECIPE_DIR%\SumatraPDF-settings.txt"
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('cxx') }}
  - m2-sed
  host:
  - harfbuzz
  - libgumbo
  - libheif
  - libunrar
  - libwebp-base
  - openjpeg
  - zlib

about:
  license_file: AUTHORS
  summary: SumatraPDF reader
