context:
  version: 3.3.3
  sha256_src: c144e0dd388db2f5e8e0b412c0d9be6c54e4db99a4575b6058a209f3603a333d
  sha256_jar: a694d49bd03e1edd4c23b3ba808bc221eb8a8ccfe7bfd2a0a884b2b2fb425188

package:
  name: pdftk
  version: ${{ version }}

source:
- url: https://gitlab.com/pdftk-java/pdftk/-/archive/v${{ version }}/pdftk-v${{ version }}.tar.bz2
  sha256: ${{ sha256_src }}
- url: https://gitlab.com/api/v4/projects/5024297/packages/generic/pdftk-java/v${{ version }}/pdftk-all.jar
  sha256: ${{ sha256_jar }}

build:
  number: 0
  skip:
  - not (win or linux)
  - build_platform != target_platform

requirements:
  run:
  - openjdk >=8.0.0

tests:
- script:
  - pdftk -version

about:
  license_file: LICENSE
  summary: A port of pdftk into java
