context:
  version: 1.8.4
  sha256: 49d0fc50ab931816f6bfc1ac68f8d74b760450eebdb5374e803ee36550f26774

package:
  name: libgit2
  version: ${{ version }}

source:
  url: https://codeload.github.com/libgit2/libgit2/tar.gz/v${{ version }}
  sha256: ${{ sha256 }}

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - cmake >=3.5.1
  - ${{ compiler('c') }}
  host:
  - zlib
  run:
  - openssh

tests:
- script:
  - git2 --version

about:
  license_file: COPYING
  summary: libgit2 is a portable, pure C implementation of the Git core methods provided as a re-entrant linkable library with a solid API, allowing you to write native speed custom Git applications in any language which supports C bindings.
