context:
  version: 7.5.0
  sha256: 599b4b5bda3639d667bd420a4e21110ed44e08a014e92532c2fe6c2ce64d21db
  dotnet_version: '9.0'

package:
  name: powershell
  version: ${{ version }}

source:
  url: https://mirrors.sdu.edu.cn/github-release/PowerShell_PowerShell/v${{ version }}/PowerShell-${{ version }}-win-fxdependentWinDesktop.zip
  sha256: ${{ sha256 }}

build:
  script: pwsh -NoProfile "%RECIPE_DIR%\build.ps1"
  number: 0
  skip:
  - not win

requirements:
  build:
  - m2-coreutils
  host:
  - dotnet-desktop ${{ dotnet_version }}.*
  run:
  - dotnet-desktop ${{ dotnet_version }}.*

tests:
- script:
  - pwsh -v

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
