context:
  version: 7.5.1
  sha256: 1482ddf4eb2e065bf5bd5104749aa52ad7aad1c21733a65bb0eb4b19addab2d8
  dotnet_version: '9.0'

package:
  name: powershell
  version: ${{ version }}

source:
  url: https://github.com/PowerShell/PowerShell/releases/download/v${{ version }}/PowerShell-${{ version }}-win-fxdependentWinDesktop.zip
  sha256: ${{ sha256 }}

build:
  script: pwsh -NoProfile "%RECIPE_DIR%\build.ps1"
  number: 0
  skip:
  - not win

requirements:
  build:
  - m2-coreutils
  host:
  - dotnet-desktop ${{ dotnet_version }}.*
  run:
  - dotnet-desktop ${{ dotnet_version }}.*

tests:
- script:
  - pwsh -v

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
