context:
  version: 7.4.3
  sha256: 7040504501d3ebcfe3a5f92669dfe28c53448be8f7c19e660ad6827c7bf41420
  dotnet_version: '8.0'

package:
  name: powershell
  version: ${{ version }}

source:
  url: https://mirrors.sdu.edu.cn/github-release/PowerShell_PowerShell/v${{ version }}/PowerShell-${{ version }}-win-fxdependentWinDesktop.zip
  sha256: ${{ sha256 }}

build:
  script: pwsh -NoProfile "%RECIPE_DIR%\build.ps1"
  number: 0
  skip:
  - not win

requirements:
  build:
  - python
  host:
  - dotnet-desktop ${{ dotnet_version }}.*
  - m2-coreutils
  run:
  - dotnet-desktop ${{ dotnet_version }}.*

tests:
- script:
  - pwsh -v

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
