context:
  version: 7.4.7
  sha256: 5a362bb42146673a57c193d424e1a84c449e204eab1a8dbcdc699f9da3fc690d
  dotnet_version: '8.0'

package:
  name: powershell
  version: ${{ version }}

source:
  url: https://github.com/PowerShell/PowerShell/releases/download/v${{ version }}/PowerShell-${{ version }}-win-fxdependentWinDesktop.zip
  sha256: ${{ sha256 }}

build:
  script: pwsh -NoProfile "%RECIPE_DIR%\build.ps1"
  number: 0
  skip:
  - not win

requirements:
  build:
  - m2-coreutils
  - python
  host:
  - dotnet-desktop ${{ dotnet_version }}.*
  run:
  - dotnet-desktop ${{ dotnet_version }}.*

tests:
- script:
  - pwsh -v

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
