context:
  version: 1.28.0
  sha256: c6b5c6b086c0df9d3ca3ff5e084c1d0ef909e6038279c71c1c3e985f576ff76a

package:
  name: nginx
  version: ${{ version }}

source:
  url: https://nginx.org/download/nginx-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
    env:
      MSYS2_PATH_TYPE: inherit
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - m2-base
  host:
  - openssl
  - pcre2

tests:
- script:
  - nginx -V

about:
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
