context:
  version: 1.29.6
  sha256: 316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7

package:
  name: nginx
  version: ${{ version }}

source:
  url: https://nginx.org/download/nginx-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
    content:
    - bash -el "%RECIPE_DIR%\build.sh"
    env:
      CHERE_INVOKING: '1'
      MSYS2_PATH_TYPE: inherit
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - m2-base
  host:
  - openssl
  - pcre2

tests:
- script:
  - nginx -V

about:
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
