context:
  version: 1.25.5
  sha256: a907ace01448d9bd6d9cc132afe8b159869e8e6d0a1a6f6b3e6b15c72ad88d41

package:
  name: nginx
  version: '{{ version }}'

source:
- url: https://github.com/nginx/nginx/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'
  patches:
  - 0001-conda-build.patch

build:
  include_recipe: false
  number: 0
  script_env:
    CHERE_INVOKING: '1'
    MSYS2_PATH_TYPE: inherit
  skip:
  - not win64
  - build_platform != target_platform

requirements:
  build:
  - "{{ compiler('c') }}"
  host:
  - openssl
  - posix
  run:
  - openssl

test:
  commands:
  - nginx -V

about:
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
