context:
  version: 1.27.1
  sha256: bd7ba68a6ce1ea3768b771c7e2ab4955a59fb1b1ae8d554fedb6c2304104bdfc

package:
  name: nginx
  version: ${{ version }}

source:
  url: https://mirrors.huaweicloud.com/nginx/nginx-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
    env:
      MSYS2_PATH_TYPE: inherit
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:3] == 'gcc'

requirements:
  build:
  - ${{ compiler('c') }}
  host:
  - openssl
  - pcre2
  - posix

tests:
- script:
  - nginx -V

about:
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
