context:
  version: 1.27.3
  sha256: ba23a9568f442036b61cd0e29bd66a47b90634efa91e0b2cf2d719057a9b7903

package:
  name: nginx
  version: ${{ version }}

source:
  url: https://mirrors.huaweicloud.com/nginx/nginx-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
    env:
      MSYS2_PATH_TYPE: inherit
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - m2-base
  host:
  - openssl
  - pcre2

tests:
- script:
  - nginx -V

about:
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
