context:
  version: 1.27.0
  sha256: cc1eeb4385a7313a9a22e5909a2fd1ba8f2467ec608294d295397b64b03191de

package:
  name: nginx
  version: ${{ version }}

source:
- url: https://github.com/nginx/nginx/archive/refs/tags/release-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform

requirements:
  build:
  - ${{ compiler('c') }}
  host:
  - openssl
  - pcre2
  - posix

tests:
- script:
  - nginx -V

about:
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
