context:
  version: 1.26.0
  sha256: 0b4263d779b5f265342dc4060b3a9bbb7df90df3253140e2ff33dcd558c27cfb

package:
  name: nginx
  version: '{{ version }}'

source:
- url: https://github.com/nginx/nginx/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'
  patches:
  - 0001-conda-build.patch

build:
  include_recipe: false
  number: 0
  script_env:
    CHERE_INVOKING: '1'
    MSYS2_PATH_TYPE: inherit
  skip:
  - not win64
  - build_platform != target_platform

requirements:
  build:
  - "{{ compiler('c') }}"
  host:
  - openssl
  - pcre2
  - posix
  run:
  - openssl

test:
  commands:
  - nginx -V

about:
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
