context:
  version: 1.29.4
  sha256: 5a7d37eee505866fbab5810fa9f78247d6d5d9157a595c4e7a72043141ddab25

package:
  name: nginx
  version: ${{ version }}

source:
  url: https://nginx.org/download/nginx-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
    content:
    - bash -el "%RECIPE_DIR%\build.sh"
    env:
      CHERE_INVOKING: '1'
      MSYS2_PATH_TYPE: inherit
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - m2-base
  host:
  - openssl
  - pcre2

tests:
- script:
  - nginx -V

about:
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
