context:
  # curl https://open-vsx.org/api/astral-sh/ty/win32-x64/versions?size=1
  version: 2025.51.13022037
  # curl -L https://open-vsx.org/api/astral-sh/ty/win32-x64/latest/file/sha256
  sha256: 1eab56d43a920f71fc691c8695594601f13eb9c8461c4d7e7d7cc336dafb7bb6

package:
  name: ty-vscode
  version: ${{ version }}

source:
  url: https://open-vsx.org/api/astral-sh/ty/win32-x64/${{ version }}/file/astral-sh.ty-${{ version }}@win32-x64.vsix
  sha256: ${{ sha256 }}

build:
  number: 0
  script:
  - md "%LIBRARY_PREFIX%\opt\vscodium\bootstrap\extensions"
  - mklink /H "%LIBRARY_PREFIX%\opt\vscodium\bootstrap\extensions\astral-sh.ty-${{ version }}@win32-x64.vsix" astral-sh.ty-${{ version }}@win32-x64.vsix
  skip:
  - not win
  - build_platform != target_platform

requirements:
  run:
  - vscodium >=1.103.15539
  run_constraints:
  - vscode-pyright <0a0

about:
  license: MIT
  license_family: MIT
  summary: A Visual Studio Code extension with support for the ty type checker and language server
