context:
  svn_rev: 4453
  version: 4.9.9dev${{ svn_rev }}
  sha256: 3015437d1a6a3b7facd21d098dfb1f6b6b64eee9bceb9c915e728423cb9df4b3

package:
  name: akelpad
  version: ${{ version }}

source:
- url: https://sourceforge.net/code-snapshots/svn/a/ak/akelpad/codesvn/akelpad-codesvn-r${{ svn_rev }}-trunk-akelpad_4.zip
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch
- path: CMakeLists.txt

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:3] == 'gcc'

requirements:
  build:
  - cmake >=3.21.0
  - ${{ compiler('c') }}

about:
  license_family: BSD
  summary: A simple notepad-like text editor with many features
