context:
  version: 4.9.9
  sha256: 40ab1d49d822f7abe67ceeb8c37bdb357b7f068827faddf871c4771dccdfa746

package:
  name: akelpad
  version: ${{ version }}

source:
- url: https://jaist.dl.sourceforge.net/project/akelpad/AkelPad%204/${{ version }}/AkelPad-${{ version }}-src.zip
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch
- path: CMakeLists.txt

build:
  number: 1
  script:
  - if: compiler('c') is startingwith('vs')
    then:
    - '"%RECIPE_DIR%\build.bat"'
    else:
    - set CHERE_INVOKING=1
    - set MSYS2_PATH_TYPE=inherit
    - bash -el "%RECIPE_DIR%\build.sh"
  skip:
  - not win
  - build_platform != target_platform

requirements:
  build:
  - ${{ compiler('c') }}
  - if: compiler('c') is startingwith('vs')
    then:
    - cmake >=3.21.0
    else:
    - m2-base
    - m2-diffutils
  host:
  - if: not (compiler('c') is startingwith('vs'))
    then:  # Shadowed by msys2 if installed into build env
    - cmake >=3.21.0
    - ninja
  ignore_run_exports:
    from_package:
    - if: not (compiler('c') is startingwith('vs'))
      then: ${{ compiler('c') }}

about:
  license_family: BSD
  summary: A simple notepad-like text editor with many features
