context:
  version: 4.9.9
  sha256: 40ab1d49d822f7abe67ceeb8c37bdb357b7f068827faddf871c4771dccdfa746

package:
  name: akelpad
  version: '{{ version }}'

source:
- url: https://jaist.dl.sourceforge.net/project/akelpad/AkelPad%204/{{ version }}/AkelPad-{{ version }}-src.zip
  sha256: '{{ sha256 }}'
  patches:
  - 0001-customize.patch
- path: CMakeLists.txt

build:
  include_recipe: false
  number: 1
  skip:
  - not win
  - build_platform != target_platform

requirements:
  build:
  - cmake >=3.21.0
  - "{{ compiler('c') }}"

about:
  license_family: BSD
  summary: A simple notepad-like text editor with many features
