context:
  version: 0.4.15
  sha256: 317a1d17798c45d5e81facd0f910aa6f1457826c4cc359fed8011d116f194043

package:
  name: cmd
  version: ${{ version }}

source:
  url: https://github.com/reactos/reactos/archive/refs/tags/${{ version }}-release.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - compiler('cxx')[:2] != 'vs'

requirements:
  build:
  - cmake
  - ${{ compiler('cxx') }}
  - ninja
  - winflexbison

about:
  license_file:
  - COPYING
  - base/shell/cmd/license.txt
