context:
  version: 0.4.15
  sha256: 317a1d17798c45d5e81facd0f910aa6f1457826c4cc359fed8011d116f194043

package:
  name: cmd
  version: ${{ version }}

source:
  url: https://codeload.github.com/reactos/reactos/tar.gz/${{ version }}-release
  sha256: ${{ sha256 }}

build:
  number: 0
  script:
  - call configure.cmd %CMAKE_ARGS%
  - cd output-VS-amd64
  - ninja base\shell\cmd\cmd.exe
  - mklink /H "%LIBRARY_BIN%\cmd.exe" base\shell\cmd\cmd.exe
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - cmake >=3.17.0,<4
  - ${{ compiler('cxx') }}
  - ninja
  - winflexbison

about:
  license_file:
  - COPYING
  - base/shell/cmd/license.txt
