context:
  version: 0.1.14
  sha256: 818624ef2df72094b167cfbac9c3ab2e998f49014ae8f926cf52230857990bf5

recipe:
  name: pixi-build-backends
  version: ${{ version }}

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

cache:
  source:
  - url: https://github.com/prefix-dev/pixi-build-backends/archive/refs/tags/pixi-build-rust-v${{ version }}.tar.gz
    sha256: ${{ sha256 }}
    target_directory: pixi-build-backends
    patches:
    - 0001-customize.patch
  - url: https://github.com/prefix-dev/pixi/archive/1ca9578b0ad73dbd5a889849f3bff47ddb91a81f.tar.gz
    sha256: 7f7b8a4b4fdfe393266cc930403469cf2d73a9a822f3d796c873044909f02282
    target_directory: pixi
  - url: https://github.com/prefix-dev/rattler-build/archive/ea03f64d243260dfd06e7ec75e015233ae9e2bd2.tar.gz
    sha256: e3dec3a3f67abd309543838e69c11dc14f3cc2237ac31d1817cc3ecf67308e89
    target_directory: rattler-build
  requirements:
    build:
    - ${{ compiler('c') }}
    - rust >=1.86.0
    - if: linux
      then: diffutils
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}

outputs:
- package:
    name: pixi-build-cmake
  build:
    files:
    - bin/pixi-build-cmake
    - Library/bin/pixi-build-cmake.exe
  tests:
  - script:
    - pixi-build-cmake help
- package:
    name: pixi-build-python
  build:
    files:
    - bin/pixi-build-python
    - Library/bin/pixi-build-python.exe
  tests:
  - script:
    - pixi-build-python help
- package:
    name: pixi-build-rattler-build
  build:
    files:
    - bin/pixi-build-rattler-build
    - Library/bin/pixi-build-rattler-build.exe
  tests:
  - script:
    - pixi-build-rattler-build help
- package:
    name: pixi-build-rust
  build:
    files:
    - bin/pixi-build-rust
    - Library/bin/pixi-build-rust.exe
  tests:
  - script:
    - pixi-build-rust help
