context:
  version: 0.3.7
  sha256: 25cadd0551e18d6bc1f279a94038d8f2e36eb2cd5f6f7d0c727400d4426dcfbe

recipe:
  name: pixi-build-backends
  version: ${{ version }}

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

cache:
  source:
  - url: https://codeload.github.com/prefix-dev/pixi-build-backends/tar.gz/pixi-build-cmake-v${{ version }}
    sha256: ${{ sha256 }}
    target_directory: pixi-build-backends
    patches:
    - 0001-customize.patch
  - url: https://codeload.github.com/prefix-dev/rattler-build/tar.gz/5d1ec04ea015e1fe2917b38a4491dbdffa29ec18
    sha256: 8f2105733869d96c07db2a8f68a4755ecfcf2fc5d5c9620df45cd56b173d02f5
    target_directory: rattler-build
    patches:
    - 0001-conda-build.patch
  requirements:
    build:
    - ${{ compiler('c') }}
    - rust >=1.89.0
    - if: linux
      then: diffutils
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}
  build:
    script:
    - if: win
      then:
      - cargo install --locked --no-track --path pixi-build-backends/crates/pixi-build-cmake --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path pixi-build-backends/crates/pixi-build-mojo --root "%LIBRARY_PREFIX%"
      - cargo install --locked --no-track --path pixi-build-backends/crates/pixi-build-python --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path pixi-build-backends/crates/pixi-build-rattler-build --root "%LIBRARY_PREFIX%"
      - cargo install --locked --no-track --path pixi-build-backends/crates/pixi-build-rust --root "%LIBRARY_PREFIX%"
      else:
      - cargo install --locked --no-track --path pixi-build-backends/crates/pixi-build-cmake --root "$PREFIX"
      - cargo install --frozen --no-track --path pixi-build-backends/crates/pixi-build-mojo --root "$PREFIX"
      - cargo install --locked --no-track --path pixi-build-backends/crates/pixi-build-python --root "$PREFIX"
      - cargo install --frozen --no-track --path pixi-build-backends/crates/pixi-build-rattler-build --root "$PREFIX"
      - cargo install --locked --no-track --path pixi-build-backends/crates/pixi-build-rust --root "$PREFIX"

outputs:
- package:
    name: pixi-build-cmake
  build:
    files:
    - bin/pixi-build-cmake
    - Library/bin/pixi-build-cmake.exe
  tests:
  - script:
    - pixi-build-cmake help
- package:
    name: pixi-build-mojo
  build:
    files:
    - bin/pixi-build-mojo
    - Library/bin/pixi-build-mojo.exe
  tests:
  - script:
    - pixi-build-mojo help
- package:
    name: pixi-build-python
  build:
    files:
    - bin/pixi-build-python
    - Library/bin/pixi-build-python.exe
  tests:
  - script:
    - pixi-build-python help
- package:
    name: pixi-build-rattler-build
  build:
    files:
    - bin/pixi-build-rattler-build
    - Library/bin/pixi-build-rattler-build.exe
  tests:
  - script:
    - pixi-build-rattler-build help
- package:
    name: pixi-build-rust
  build:
    files:
    - bin/pixi-build-rust
    - Library/bin/pixi-build-rust.exe
  tests:
  - script:
    - pixi-build-rust help

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Backend implementations to build Pixi projects from source
