context:
  version: 0.2.0
  sha256: c68afa9715980dcb233f9591fca4b26b37696d089536d30217dca0eb8c14772b

recipe:
  name: pixi-build-backends
  version: ${{ version }}

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

cache:
  source:
  - url: https://codeload.github.com/prefix-dev/pixi-build-backends/tar.gz/pixi-build-rattler-build-v${{ version }}
    sha256: ${{ sha256 }}
    target_directory: pixi-build-backends
    patches:
    - 0001-customize.patch
  - url: https://codeload.github.com/prefix-dev/pixi/tar.gz/1ca9578b0ad73dbd5a889849f3bff47ddb91a81f
    sha256: 7f7b8a4b4fdfe393266cc930403469cf2d73a9a822f3d796c873044909f02282
    target_directory: pixi
  - url: https://codeload.github.com/prefix-dev/rattler-build/tar.gz/ea03f64d243260dfd06e7ec75e015233ae9e2bd2
    sha256: e3dec3a3f67abd309543838e69c11dc14f3cc2237ac31d1817cc3ecf67308e89
    target_directory: rattler-build
    patches:
    - 0001-conda-build.patch
  requirements:
    build:
    - ${{ compiler('c') }}
    - rust >=1.86.0
    - if: linux
      then: diffutils
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}

outputs:
- package:
    name: pixi-build-cmake
  build:
    files:
    - bin/pixi-build-cmake
    - Library/bin/pixi-build-cmake.exe
  tests:
  - script:
    - pixi-build-cmake help
- package:
    name: pixi-build-python
  build:
    files:
    - bin/pixi-build-python
    - Library/bin/pixi-build-python.exe
  tests:
  - script:
    - pixi-build-python help
- package:
    name: pixi-build-rattler-build
  build:
    files:
    - bin/pixi-build-rattler-build
    - Library/bin/pixi-build-rattler-build.exe
  tests:
  - script:
    - pixi-build-rattler-build help
- package:
    name: pixi-build-rust
  build:
    files:
    - bin/pixi-build-rust
    - Library/bin/pixi-build-rust.exe
  tests:
  - script:
    - pixi-build-rust help
