context:
  version: 0.1.3
  sha256: 77f46106c885442ac346bb19b964abe354fb600599fef36619172613f161e133
  pixi_version: 0.41.4
  pixi_sha256: 569e015e2281713dd65175febd077f4544ad6c42d9bf50e2e9febcaa792a0718
  rattler_build_version: 0.36.0
  rattler_build_sha256: bc99bee1fa07926cc4cfa8995522bca65210df158cc2bf2564a8e3da211d231a

recipe:
  name: pixi-build-backends
  version: ${{ version }}

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and compiler('c')[:2] != 'vs'

cache:
  source:
  - url: https://github.com/prefix-dev/pixi-build-backends/archive/refs/tags/v${{ version }}.tar.gz
    sha256: ${{ sha256 }}
    target_directory: pixi-build-backends
    patches:
    - 0001-customize.patch
  - url: https://github.com/prefix-dev/pixi/archive/refs/tags/v${{ pixi_version }}.tar.gz
    sha256: ${{ pixi_sha256 }}
    target_directory: pixi
  - url: https://github.com/prefix-dev/rattler-build/archive/refs/tags/v${{ rattler_build_version }}.tar.gz
    sha256: ${{ rattler_build_sha256 }}
    target_directory: rattler-build
  requirements:
    build:
    - ${{ compiler('c') }}
    - rust ==1.84.0
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}

outputs:
- package:
    name: pixi-build-cmake
  build:
    files:
    - bin/pixi-build-cmake
    - Library/bin/pixi-build-cmake.exe
  tests:
  - script:
    - pixi-build-cmake help
- package:
    name: pixi-build-python
  build:
    files:
    - bin/pixi-build-python
    - Library/bin/pixi-build-python.exe
  tests:
  - script:
    - pixi-build-python help
- package:
    name: pixi-build-rattler-build
  build:
    files:
    - bin/pixi-build-rattler-build
    - Library/bin/pixi-build-rattler-build.exe
  tests:
  - script:
    - pixi-build-rattler-build help
