context:
  version: 0.1.5
  sha256: a0773ec33289bb7def34d57df364a9d761d50c018c392bdffd16318bdb2f88de

recipe:
  name: pixi-build-backends
  version: ${{ version }}

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and compiler('c')[:2] != 'vs'

cache:
  source:
  - url: https://github.com/prefix-dev/pixi-build-backends/archive/refs/tags/pixi-build-rust-v${{ version }}.tar.gz
    sha256: ${{ sha256 }}
    target_directory: pixi-build-backends
    patches:
    - 0001-customize.patch
  - url: https://github.com/prefix-dev/pixi/archive/a43ce5509671fea2449b1f6d24a11cee2660a01c.tar.gz
    sha256: 723e7b6f47af0bffb22fc3c4a5da7f0c4931c769e0036268a08a4d0bdd797ee5
    target_directory: pixi
  - url: https://github.com/prefix-dev/rattler-build/archive/674439811c9b67c5928115a594fa168f0eee0cbc.tar.gz
    sha256: 9bd34172d47cc9aab1f36ae174eba83cbe519630b3ded44ad53fe03593521611
    target_directory: rattler-build
  requirements:
    build:
    - ${{ compiler('c') }}
    - rust ==1.84.0
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}

outputs:
- package:
    name: pixi-build-cmake
  build:
    files:
    - bin/pixi-build-cmake
    - Library/bin/pixi-build-cmake.exe
  tests:
  - script:
    - pixi-build-cmake help
- package:
    name: pixi-build-python
  build:
    files:
    - bin/pixi-build-python
    - Library/bin/pixi-build-python.exe
  tests:
  - script:
    - pixi-build-python help
- package:
    name: pixi-build-rattler-build
  build:
    files:
    - bin/pixi-build-rattler-build
    - Library/bin/pixi-build-rattler-build.exe
  tests:
  - script:
    - pixi-build-rattler-build help
- package:
    name: pixi-build-rust
  build:
    files:
    - bin/pixi-build-rust
    - Library/bin/pixi-build-rust.exe
  tests:
  - script:
    - pixi-build-rust help
