context:
  year: 2025
  month: '08'
  day: 31
  sha256: 9bc7415989516d01976c65074f085c5f4e471a676f284cbc30b1966b50021c58

package:
  name: ruffle
  version: 0.2.0dev${{ year }}${{ month }}${{ day }}

source:
- url: https://codeload.github.com/ruffle-rs/ruffle/tar.gz/nightly-${{ year }}-${{ month }}-${{ day }}
  sha256: ${{ sha256 }}
  target_directory: ruffle
  patches:
  - 0001-customize.patch
- url: https://codeload.github.com/emilk/egui/tar.gz/78a8de2e8f8d6da82680af4701cfa6e61cfe389c
  sha256: 0fe6e8b3d7d45dfe90aaad060bd2886cab92c45666242deaa4faceb06821aa17
  target_directory: egui
- url: https://codeload.github.com/kyren/gc-arena/tar.gz/08e08414249d5914dfc3b402d7eadc133e00ce56
  sha256: fe22a154660b52f622dafd3c378716633271bc851873602dc6100bf699f88d0e
  target_directory: gc-arena
- url: https://codeload.github.com/ruffle-rs/h263-rs/tar.gz/b3f905511acc7b80861dac45fdc5ca913b6029e5
  sha256: ad6ef55b8c955fa0e134c9d039deb1c65d07c01f7dab2b61970da01a782b1275
  target_directory: h263-rs
- url: https://codeload.github.com/ruffle-rs/jpegxr/tar.gz/2a429b0d71ab416e10b73d4dbdcf34cfe2900395
  sha256: 1091a188d1a6459dff64459a9131ff9d81ec314af59f6576fe2a78f4b7d74661
  target_directory: jpegxr
- url: https://codeload.github.com/ruffle-rs/nellymoser/tar.gz/073eb48d907201f46dea0c8feb4e8d9a1d92208c
  sha256: 5f9887074040e226cf2b2e3eb4ee0dc11555a9a0cf3c3db3ab50d7389c5790a5
  target_directory: nellymoser
- url: https://codeload.github.com/ruffle-rs/nihav-vp6/tar.gz/83c7e1094d603d9fc1212d39d99abb17f3a3226b
  sha256: b23849bc98fec53b8aa4467cc49e73ab3e87f635a7e1d0738542e5e81a5a885d
  target_directory: nihav-vp6
- url: https://codeload.github.com/ruffle-rs/regras3/tar.gz/5fcb02513c5ab4e00df4346459f5a8d0521d8fed
  sha256: f71851c5a8c944f788c2771f506c88f39c1397d695f919562de81b4c3efde753
  target_directory: regras3
- url: https://codeload.github.com/ruffle-rs/rust-flash-lso/tar.gz/998f47c926b9986aabd518fbb7394ff56936d0b0
  sha256: f6aa0244047019e5b15a1c30bbed6bc26c5c128628b17ff5b2047f4799401dc7
  target_directory: rust-flash-lso
- url: https://codeload.github.com/KyleMayes/clang-sys/tar.gz/v1.8.1
  sha256: f3571b3033fc6ff32f86326de724ece3ced7867f2016ccf7cdb36284d3f9c9b8
  target_directory: clang-sys
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
  - set "LIBCLANG_PATH=%BUILD_PREFIX%\Library\bin\libclang-13.dll"
  - cd ruffle
  - cargo build --release -F jpegxr
  - mklink /H "%LIBRARY_BIN%\ruffle.exe" target\release\ruffle_desktop.exe
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - libclang13
  - openjdk
  - rust
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  run:
  - openh264 ==2.4.1

tests:
- script:
  - ruffle -V

about:
  license_file: ruffle/LICENSE.md
  summary: A Flash Player emulator written in Rust
