context:
  year: 2026
  month: '03'
  day: 26
  sha256: cae42da4ecef5b84172af81420941f83f32dd5c3b5f69b37a053c6c920dbb0d0

package:
  name: ruffle
  version: 0.2.0dev${{ year }}${{ month }}${{ day }}

source:
- url: https://codeload.github.com/ruffle-rs/ruffle/tar.gz/nightly-${{ year }}-${{ month }}-${{ day }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch
- url: https://codeload.github.com/KyleMayes/clang-sys/tar.gz/v1.8.1
  sha256: f3571b3033fc6ff32f86326de724ece3ced7867f2016ccf7cdb36284d3f9c9b8
  target_directory: clang-sys
  patches:
  - 0001-conda-build.patch

build:
  number: 0
  script:
  - set "LIBCLANG_PATH=%BUILD_PREFIX%\Library\bin\libclang-13.dll"
  - cargo install -F jpegxr --locked --no-track --path desktop --root "%LIBRARY_PREFIX%"
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - libclang13 21.*
  - openjdk
  - rust >=1.89.0
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  run:
  - openh264 ==2.4.1

tests:
- script:
  - ruffle -V

about:
  license_file: LICENSE.md
  summary: A Flash Player emulator written in Rust
