# TO BUILD THIS RECIPE:
# - on windows, long paths must(?) be enabled, see
#   https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

context:
  version: 0.27.7  # rattler>=0.27.8 requires rust>=1.80.0
  sha256: 480509dc680865b5185a231131a6fb35041a23403e3956637e047d92130f2119

package:
  name: rattler-cli
  version: ${{ version }}

source:
- url: https://github.com/conda/rattler/archive/refs/tags/rattler-v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch
- url: https://github.com/baszalmstra/libsolv/archive/refs/heads/master.tar.gz
  sha256: 74ec1fd3f701d2f06be7f79d7513830dd94f32426c34f774951dd4bd82ccdcca
  target_directory: crates/rattler_libsolv_c/libsolv

build:
  number: 0
  script:
  - cd crates/rattler-bin
  - cargo build --all-features --release
  - if: win
    then:
    - mklink /H "%LIBRARY_BIN%\rattler.exe" ..\..\target\release\rattler.exe
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:2] != 'vs'

requirements:
  build:
  - cmake
  - ${{ compiler('c') }}
  - rust 1.75.0

tests:
- script:
  - rattler -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
