context:
  version: 0.27.7  # rattler>=0.27.8 requires rust>=1.80.0
  sha256: 480509dc680865b5185a231131a6fb35041a23403e3956637e047d92130f2119

package:
  name: rattler-cli
  version: ${{ version }}

source:
- url: https://github.com/conda/rattler/archive/refs/tags/rattler-v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch
- url: https://github.com/baszalmstra/libsolv/archive/refs/heads/master.tar.gz
  sha256: 74ec1fd3f701d2f06be7f79d7513830dd94f32426c34f774951dd4bd82ccdcca
  target_directory: crates/rattler_libsolv_c/libsolv

build:
  number: 1
  script:
  - cargo update litemap --precise 0.7.4
  - cargo update native-tls --precise 0.2.13
  - cargo update reflink-copy --precise 0.1.21
  - cargo update zerofrom --precise 0.1.5
  - if: win
    then:
    - cargo install --all-features --locked --no-track --path crates/rattler-bin --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --all-features --locked --no-track --path crates/rattler-bin --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - cmake
  - ${{ compiler('c') }}
  - rust ==1.75.0
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}

tests:
- script:
  - rattler -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
