context:
  version: 1.112.01907
  sha256: 6dcfc1e7f2a74ad236f1622eed673b9777bec7451282fee0c5a2731bcf296445
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/versions?size=1
  cmake_version: 0.7.1
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/latest/file/sha256
  cmake_sha256: 4ff4b7fd7919799c6e48a1ebca6ad8f4f9bee8a1615c125aa8fab14680861aec
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/versions?size=1
  clangd_version: 0.4.0
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/latest/file/sha256
  clangd_sha256: afbd4f002b89641012b166051caa2af2f56ed732b7dbf4bc00a56d0891e41aa9
  # https://api.github.com/repos/mathworks/MATLAB-extension-for-vscode/releases/latest
  # matlab_version: 1.3.8
  # matlab_sha256: 58e4c73b48a4eb3c5926b833c0164360977b8eddd38afeeaa3a7bf0eb1ad4d3f
  # https://open-vsx.org/api/ms-python/python/versions?size=1
  python_version: 2026.4.0
  # https://open-vsx.org/api/ms-python/python/latest/file/sha256
  python_sha256: 232aeafb01f069824fdd92d3e628c1c442bbcfa1d3cc945ff97076340bb2b4a6
  # https://api.github.com/repos/whoami730/cython-enhanced/releases/latest
  cython_version: 1.0.5
  cython_sha256: 423715d7efbac30a5db53eb0eb64afe08b9ec7d462613b3622b96ccec3bfa54b
  # https://open-vsx.org/api/charliermarsh/ruff/win32-x64/versions?size=1
  ruff_version: 2026.38.0
  # https://open-vsx.org/api/charliermarsh/ruff/win32-x64/latest/file/sha256
  ruff_sha256: 05b310206dd124d8af70316667c046f07899ec7da6a511a6b5ae91a252efc3be
  # https://open-vsx.org/api/tombi-toml/tombi/win32-x64/versions?size=1
  toml_version: 0.9.9
  # https://open-vsx.org/api/tombi-toml/tombi/win32-x64/latest/file/sha256
  toml_sha256: 738fe99d1912bb6c282e2d8f7a24b5a71379e4aaf798f5a0c48cc14964111b90

package:
  name: vscodium
  version: ${{ version }}

source:
- url: https://github.com/VSCodium/VSCodium/releases/download/${{ version }}/VSCodium-win32-x64-${{ version }}.zip
  sha256: ${{ sha256 }}
  target_directory: vscodium
  patches:
  - 0001-customize.patch
- url: https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/${{ cmake_version }}/file/KylinIdeTeam.cmake-intellisence-${{ cmake_version }}.vsix
  sha256: ${{ cmake_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/${{ clangd_version }}/file/llvm-vs-code-extensions.vscode-clangd-${{ clangd_version }}.vsix
  sha256: ${{ clangd_sha256 }}
  target_directory: vscodium/bootstrap/extensions
# - url: https://github.com/mathworks/MATLAB-extension-for-vscode/releases/download/v${{ matlab_version }}/language-matlab-${{ matlab_version }}.vsix
#   sha256: ${{ matlab_sha256 }}
#   target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/ms-python/python/${{ python_version }}/file/ms-python.python-${{ python_version }}.vsix
  sha256: ${{ python_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://github.com/whoami730/cython-enhanced/releases/download/${{ cython_version }}/cython-enhanced.vsix
  sha256: ${{ cython_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/charliermarsh/ruff/win32-x64/${{ ruff_version }}/file/charliermarsh.ruff-${{ ruff_version }}@win32-x64.vsix
  sha256: ${{ ruff_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/tombi-toml/tombi/win32-x64/${{ toml_version }}/file/tombi-toml.tombi-${{ toml_version }}@win32-x64.vsix
  sha256: ${{ toml_sha256 }}
  target_directory: vscodium/bootstrap/extensions

build:
  number: 0
  script:
  - md "%LIBRARY_PREFIX%\opt"
  - cp -al vscodium "%LIBRARY_PREFIX%\opt"
  skip:
  - not win
  - build_platform != target_platform

requirements:
  host:
  - m2-coreutils
  - vc

tests:
- script:
  - '"%CONDA_PREFIX%\Library\opt\vscodium\bin\codium.cmd" --version'

about:
  license: MIT
  license_family: MIT
  summary: binary releases of VS Code without MS branding/telemetry/licensing
