context:
  version: 1.95.2
  version_full: ${{ version }}.24313
  sha256: bdeab62d166d1acf9a510db63795e292d435809cd099389de949ebd4e42f1a75

package:
  name: vscodium
  version: ${{ version }}

source:
  url: https://mirror.nju.edu.cn/github-release/VSCodium/vscodium/${{ version_full }}/VSCodium-win32-x64-${{ version_full }}.zip
  sha256: ${{ sha256 }}

build:
  number: 0
  skip:
  - not win

requirements:
  host:
  - m2-coreutils

tests:
- script:
  - code --version

about:
  license: MIT
  license_family: MIT
  summary: binary releases of VS Code without MS branding/telemetry/licensing
