context:
  version: 1.103.15539
  sha256: 6b1057af5aed8e686f03b9c334dab7b2233bcabcece1bf5f9fa782ed79ba9ffc
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/versions?size=1
  cmake_version: 0.4.0
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/latest/file/sha256
  cmake_sha256: d4e40b3d59040ee57065104747e5a4b67144be053cfffaf79d3a3fb8a270e2eb
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/versions?size=1
  clangd_version: 0.2.0
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/latest/file/sha256
  clangd_sha256: a7dd3b3c8cb40f84a1b7889e54f5cdf28d220682d213f9f8d4909e23b79af017
  # https://api.github.com/repos/mathworks/MATLAB-extension-for-vscode/releases/latest
  matlab_version: 1.3.4
  matlab_sha256: 60bbb68683da14545b38a27bba925a6d1161c7244a7e2ee90f894ffb3c29355d
  # https://open-vsx.org/api/ms-python/python/versions?size=1
  python_version: 2025.4.0
  # https://open-vsx.org/api/ms-python/python/latest/file/sha256
  python_sha256: 31b22cdb399b0aaeb7705e8e38665e0c33ac3dacd13852a1a8b7fb151c728b72
  # https://api.github.com/repos/ktnrg45/vs-code-cython/releases/latest
  cython_version: 1.0.3
  cython_sha256: 68ad4e17045ce6c90ba24b8416266419582a688db63d35c6175135e9cc741034
  # https://open-vsx.org/api/charliermarsh/ruff/win32-x64/versions?size=1
  ruff_version: 2025.24.0
  # https://open-vsx.org/api/charliermarsh/ruff/win32-x64/latest/file/sha256
  ruff_sha256: c0eae4abdb4ad0827c3fc41a2859ff9de3f7940d9b11bb23ab623993dff958e9
  # https://open-vsx.org/api/tamasfe/even-better-toml/versions?size=1
  toml_version: 0.21.2
  # https://open-vsx.org/api/tamasfe/even-better-toml/latest/file/sha256
  toml_sha256: f3dc44f1c551edef397a79f0f8c5db4066c6a547e210b5c3cec4400bf173b008

package:
  name: vscodium
  version: ${{ version }}

source:
- url: https://github.com/VSCodium/VSCodium/releases/download/${{ version }}/VSCodium-win32-x64-${{ version }}.zip
  sha256: ${{ sha256 }}
  target_directory: vscodium
  patches:
  - 0001-customize.patch
- url: https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/${{ cmake_version }}/file/KylinIdeTeam.cmake-intellisence-${{ cmake_version }}.vsix
  sha256: ${{ cmake_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/${{ clangd_version }}/file/llvm-vs-code-extensions.vscode-clangd-${{ clangd_version }}.vsix
  sha256: ${{ clangd_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://github.com/mathworks/MATLAB-extension-for-vscode/releases/download/v${{ matlab_version }}/language-matlab-${{ matlab_version }}.vsix
  sha256: ${{ matlab_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/ms-python/python/${{ python_version }}/file/ms-python.python-${{ python_version }}.vsix
  sha256: ${{ python_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://github.com/ktnrg45/vs-code-cython/releases/download/${{ cython_version }}/vscode-cython.vsix
  sha256: ${{ cython_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/charliermarsh/ruff/win32-x64/${{ ruff_version }}/file/charliermarsh.ruff-${{ ruff_version }}@win32-x64.vsix
  sha256: ${{ ruff_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/tamasfe/even-better-toml/${{ toml_version }}/file/tamasfe.even-better-toml-${{ toml_version }}.vsix
  sha256: ${{ toml_sha256 }}
  target_directory: vscodium/bootstrap/extensions

build:
  number: 0
  skip:
  - not win

requirements:
  host:
  - m2-coreutils
  - vc

tests:
- script:
  - '"%CONDA_PREFIX%\Library\opt\vscodium\bin\codium.cmd" --version'

about:
  license: MIT
  license_family: MIT
  summary: binary releases of VS Code without MS branding/telemetry/licensing
