context:
  version: 1.97.2
  release: ${{ version }}.25045
  sha256: 76785a71712718d469f99ee3aeb95209aff9f1154b553e39c81a40f0f3c811c6
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/versions?size=1
  cmake_version: 0.3.3
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/latest/file/sha256
  cmake_sha256: 8b331d346d4dfc88a25f5a23fcc1c545162bffea3104caf09aab8dc5a4e26c4e
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/versions?size=1
  clangd_version: 0.1.33
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/latest/file/sha256
  clangd_sha256: 3cb5c8a0319d74900b1b703a5821691cb97c722da12065dfb99859078dcded05
  # https://open-vsx.org/api/jeff-hykin/better-m-syntax/versions?size=1
  matlab_version: 0.0.3
  # https://open-vsx.org/api/jeff-hykin/better-m-syntax/latest/file/sha256
  matlab_sha256: 4227836ef17776bd0ef178aa52a1e879905c79d8787e72163716d6802ac24fc6
  # https://open-vsx.org/api/detachhead/basedpyright/versions?size=1
  pyright_version: 1.27.1
  # https://open-vsx.org/api/detachhead/basedpyright/latest/file/sha256
  pyright_sha256: 9959d9749357ca54452b0fdfe237c3dbf7ea30bff06dad9a9359d9145b896bda
  # https://open-vsx.org/api/ms-python/python/versions?size=1
  python_version: 2025.0.0
  # https://open-vsx.org/api/ms-python/python/latest/file/sha256
  python_sha256: aef68096228d6ede1f277a6a11b1443ef088a473eb798a31c9d02247f1795707
  # https://api.github.com/repos/ktnrg45/vs-code-cython/releases/latest
  cython_version: 1.0.3
  cython_sha256: 68ad4e17045ce6c90ba24b8416266419582a688db63d35c6175135e9cc741034
  # https://open-vsx.org/api/tamasfe/even-better-toml/versions?size=1
  toml_version: 0.21.2
  # https://open-vsx.org/api/tamasfe/even-better-toml/latest/file/sha256
  toml_sha256: f3dc44f1c551edef397a79f0f8c5db4066c6a547e210b5c3cec4400bf173b008

package:
  name: vscodium
  version: ${{ version }}

source:
- url: https://mirror.nju.edu.cn/github-release/VSCodium/vscodium/${{ release }}/VSCodium-win32-x64-${{ release }}.zip
  sha256: ${{ sha256 }}
  target_directory: vscodium
- url: https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/${{ cmake_version }}/file/KylinIdeTeam.cmake-intellisence-${{ cmake_version }}.vsix
  sha256: ${{ cmake_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/${{ clangd_version }}/file/llvm-vs-code-extensions.vscode-clangd-${{ clangd_version }}.vsix
  sha256: ${{ clangd_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/jeff-hykin/better-m-syntax/${{ matlab_version }}/file/jeff-hykin.better-m-syntax-${{ matlab_version }}.vsix
  sha256: ${{ matlab_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/detachhead/basedpyright/${{ pyright_version }}/file/detachhead.basedpyright-${{ pyright_version }}.vsix
  sha256: ${{ pyright_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/ms-python/python/${{ python_version }}/file/ms-python.python-${{ python_version }}.vsix
  sha256: ${{ python_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://github.com/ktnrg45/vs-code-cython/releases/download/${{ cython_version }}/vscode-cython.vsix
  sha256: ${{ cython_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/tamasfe/even-better-toml/${{ toml_version }}/file/tamasfe.even-better-toml-${{ toml_version }}.vsix
  sha256: ${{ toml_sha256 }}
  target_directory: vscodium/bootstrap/extensions

build:
  number: 0
  skip:
  - not win

requirements:
  host:
  - m2-coreutils

tests:
- script:
  - code --version

about:
  license: MIT
  license_family: MIT
  summary: binary releases of VS Code without MS branding/telemetry/licensing
