context:
  version: 1.135.06055
  sha256: 0bec978f201238624bc9ad43966f5e201ed8afacc37d77035a822252d9c9c200
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/versions?size=1
  cmake_version: 0.8.1
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/latest/file/sha256
  cmake_sha256: 4a919b607a175c315bf095e1519e9451f6592f5e8582d3a5a80643ae16b24d33
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/versions?size=1
  clangd_version: 0.6.0
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/latest/file/sha256
  clangd_sha256: 32030694fa6c0ef438f4e4219f84677cd32f603c7faa4c71a283efc1f5b51751
  # https://open-vsx.org/api/whoami730/cython-enhanced/versions?size=1
  cython_version: 1.0.5
  # https://open-vsx.org/api/whoami730/cython-enhanced/latest/file/sha256
  cython_sha256: 423715d7efbac30a5db53eb0eb64afe08b9ec7d462613b3622b96ccec3bfa54b
  # https://open-vsx.org/api/charliermarsh/ruff/win32-x64/versions?size=1
  ruff_version: 2026.78.0
  # https://open-vsx.org/api/charliermarsh/ruff/win32-x64/latest/file/sha256
  ruff_sha256: fa299e23b1bf1cee800f7729f7352dea4f3293e3ea25727f7851e60d61a77cee
  # https://open-vsx.org/api/tombi-toml/tombi/win32-x64/versions?size=1
  toml_version: 1.5.4
  # https://open-vsx.org/api/tombi-toml/tombi/win32-x64/latest/file/sha256
  toml_sha256: dba9d41779e0e3cc8d7bf0ec17db1df08feb46f9983cd8dc522c798c753a06de
  # https://open-vsx.org/api/zensical/zensical-studio/versions?size=1
  zensical_version: 0.2.13
  # https://open-vsx.org/api/zensical/zensical-studio/latest/file/sha256
  zensical_sha256: 122123cad27c25694620482d320e0d1e596c2f78db18f4ef2f173c07aab08f96

package:
  name: vscodium
  version: ${{ version }}

source:
- url: https://github.com/VSCodium/VSCodium/releases/download/${{ version }}/VSCodium-win32-x64-${{ version }}.zip
  sha256: ${{ sha256 }}
  target_directory: vscodium
  patches:
  - 0001-customize.patch
- url: https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/${{ cmake_version }}/file/KylinIdeTeam.cmake-intellisence-${{ cmake_version }}.vsix
  sha256: ${{ cmake_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/${{ clangd_version }}/file/llvm-vs-code-extensions.vscode-clangd-${{ clangd_version }}.vsix
  sha256: ${{ clangd_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/ms-python/python/2025.4.0/file/ms-python.python-2025.4.0.vsix
  sha256: 31b22cdb399b0aaeb7705e8e38665e0c33ac3dacd13852a1a8b7fb151c728b72
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/whoami730/cython-enhanced/${{ cython_version }}/file/whoami730.cython-enhanced-${{ cython_version }}.vsix
  sha256: ${{ cython_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/charliermarsh/ruff/win32-x64/${{ ruff_version }}/file/charliermarsh.ruff-${{ ruff_version }}@win32-x64.vsix
  sha256: ${{ ruff_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/tombi-toml/tombi/win32-x64/${{ toml_version }}/file/tombi-toml.tombi-${{ toml_version }}@win32-x64.vsix
  sha256: ${{ toml_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/zensical/zensical-studio/${{ zensical_version }}/file/zensical.zensical-studio-${{ zensical_version }}.vsix
  sha256: ${{ zensical_sha256 }}
  target_directory: vscodium/bootstrap/extensions

build:
  number: 0
  script:
  - md "%LIBRARY_PREFIX%\opt"
  - cp -al vscodium "%LIBRARY_PREFIX%\opt"
  skip:
  - not win
  - build_platform != target_platform

requirements:
  host:
  - m2-coreutils
  - vc

tests:
- script:
  - '"%CONDA_PREFIX%\Library\opt\vscodium\bin\codium.cmd" --version'

about:
  license: MIT
  license_family: MIT
  summary: binary releases of VS Code without MS branding/telemetry/licensing
