context:
  version: 1.121.03429
  sha256: cde622b803be7e0e24742790a2f3583eeeadae91c9332ea78af579853625bd8d
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/versions?size=1
  cmake_version: 0.7.2
  # https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/latest/file/sha256
  cmake_sha256: 035c09baf89b4498e28e1e80746c0e31b06daec65a41890f8853c2a8270804ac
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/versions?size=1
  clangd_version: 0.6.0
  # https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/latest/file/sha256
  clangd_sha256: 32030694fa6c0ef438f4e4219f84677cd32f603c7faa4c71a283efc1f5b51751
  # https://api.github.com/repos/mathworks/MATLAB-extension-for-vscode/releases/latest
  # matlab_version: 1.3.8
  # matlab_sha256: 58e4c73b48a4eb3c5926b833c0164360977b8eddd38afeeaa3a7bf0eb1ad4d3f
  # https://open-vsx.org/api/ms-python/python/versions?size=1
  python_version: 2026.4.0
  # https://open-vsx.org/api/ms-python/python/latest/file/sha256
  python_sha256: 232aeafb01f069824fdd92d3e628c1c442bbcfa1d3cc945ff97076340bb2b4a6
  # https://api.github.com/repos/whoami730/cython-enhanced/releases/latest
  cython_version: 1.0.5
  cython_sha256: 423715d7efbac30a5db53eb0eb64afe08b9ec7d462613b3622b96ccec3bfa54b
  # https://open-vsx.org/api/charliermarsh/ruff/win32-x64/versions?size=1
  ruff_version: 2026.44.0
  # https://open-vsx.org/api/charliermarsh/ruff/win32-x64/latest/file/sha256
  ruff_sha256: 237d2e9e7767ba6871ece96b4c0e442e9c32a682e665f4764eef7ed43cb4e8b7
  # https://open-vsx.org/api/tombi-toml/tombi/win32-x64/versions?size=1
  toml_version: 0.11.7
  # https://open-vsx.org/api/tombi-toml/tombi/win32-x64/latest/file/sha256
  toml_sha256: df69f02f14f4c139585c722682c1de0332476f593b46a3f935293a69a4b20f5d

package:
  name: vscodium
  version: ${{ version }}

source:
- url: https://github.com/VSCodium/VSCodium/releases/download/${{ version }}/VSCodium-win32-x64-${{ version }}.zip
  sha256: ${{ sha256 }}
  target_directory: vscodium
  patches:
  - 0001-customize.patch
- url: https://open-vsx.org/api/KylinIdeTeam/cmake-intellisence/${{ cmake_version }}/file/KylinIdeTeam.cmake-intellisence-${{ cmake_version }}.vsix
  sha256: ${{ cmake_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/${{ clangd_version }}/file/llvm-vs-code-extensions.vscode-clangd-${{ clangd_version }}.vsix
  sha256: ${{ clangd_sha256 }}
  target_directory: vscodium/bootstrap/extensions
# - url: https://github.com/mathworks/MATLAB-extension-for-vscode/releases/download/v${{ matlab_version }}/language-matlab-${{ matlab_version }}.vsix
#   sha256: ${{ matlab_sha256 }}
#   target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/ms-python/python/${{ python_version }}/file/ms-python.python-${{ python_version }}.vsix
  sha256: ${{ python_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://github.com/whoami730/cython-enhanced/releases/download/${{ cython_version }}/cython-enhanced.vsix
  sha256: ${{ cython_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/charliermarsh/ruff/win32-x64/${{ ruff_version }}/file/charliermarsh.ruff-${{ ruff_version }}@win32-x64.vsix
  sha256: ${{ ruff_sha256 }}
  target_directory: vscodium/bootstrap/extensions
- url: https://open-vsx.org/api/tombi-toml/tombi/win32-x64/${{ toml_version }}/file/tombi-toml.tombi-${{ toml_version }}@win32-x64.vsix
  sha256: ${{ toml_sha256 }}
  target_directory: vscodium/bootstrap/extensions

build:
  number: 0
  script:
  - md "%LIBRARY_PREFIX%\opt"
  - cp -al vscodium "%LIBRARY_PREFIX%\opt"
  skip:
  - not win
  - build_platform != target_platform

requirements:
  host:
  - m2-coreutils
  - vc

tests:
- script:
  - '"%CONDA_PREFIX%\Library\opt\vscodium\bin\codium.cmd" --version'

about:
  license: MIT
  license_family: MIT
  summary: binary releases of VS Code without MS branding/telemetry/licensing
