context:
  version: 9.0.2753
  sha256: 47817dbcd9dd42baf5d6d4416ebc4f3176a710f38d51f6b27444acc73a2138c6

package:
  name: nsudodm
  version: ${{ version }}

source:
  url: https://codeload.github.com/M2TeamArchived/NSudo/tar.gz/refs/heads/master
  sha256: ${{ sha256 }}
  patches:
  - 0001-latest-msvc-compat.patch

build:
  number: 2
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('cxx') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('cxx') }}
  host:
  - mingw-w64-ucrt-x86_64-crt-git

about:
  license_file: License.md
