context:
  version: 0.71.2
  sha256: d01e4e213c9eaf9ef8d27d5606022d4dad25a4820794bfb4aee8a360a51feaf5

recipe:
  name: pixi
  version: ${{ version }}

source:
- url: https://codeload.github.com/prefix-dev/pixi/tar.gz/v${{ version }}
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - changes.patch
- url: https://codeload.github.com/conda/rattler/tar.gz/rattler-v0.46.0
  sha256: b62b0418d3e80d230caa691d1bcb15fe53e76180e5219dfbd7ad4ce018b1cbc4
  target_directory: rattler
  patches:
  - 0001-strip-dquotes.patch

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

outputs:
- staging:
    name: pixi-build
  requirements:
    build:
    - ${{ compiler('c') }}
    - rust >=1.90.0
    - if: linux
      then: diffutils
    - if: linux
      then: make
    - nasm
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}
  build:
    script:
    - cd pixi
    - cargo fetch
    - if: win
      then:
      - set AWS_LC_SYS_PREBUILT_NASM=0
      - cargo install --features performance --frozen --no-track --path crates/pixi --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path crates/pixi_build_cmake --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path crates/pixi_build_mojo --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path crates/pixi_build_python --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path crates/pixi_build_r --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path crates/pixi_build_ros --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path crates/pixi_build_rust --root "%LIBRARY_PREFIX%"
      else:
      - cargo install --features performance --frozen --no-track --path crates/pixi --root "$PREFIX"
      - cargo install --frozen --no-track --path crates/pixi_build_cmake --root "$PREFIX"
      - cargo install --frozen --no-track --path crates/pixi_build_mojo --root "$PREFIX"
      - cargo install --frozen --no-track --path crates/pixi_build_python --root "$PREFIX"
      - cargo install --frozen --no-track --path crates/pixi_build_r --root "$PREFIX"
      - cargo install --frozen --no-track --path crates/pixi_build_ros --root "$PREFIX"
      - cargo install --frozen --no-track --path crates/pixi_build_rust --root "$PREFIX"
- package:
    name: pixi
  inherit: pixi-build
  build:
    files:
    - bin/pixi
    - Library/bin/pixi.exe
  tests:
  - script:
    - pixi -V
- package:
    name: pixi-build-cmake
  inherit: pixi-build
  build:
    files:
    - bin/pixi-build-cmake
    - Library/bin/pixi-build-cmake.exe
  tests:
  - script:
    - pixi-build-cmake help
- package:
    name: pixi-build-mojo
  inherit: pixi-build
  build:
    files:
    - bin/pixi-build-mojo
    - Library/bin/pixi-build-mojo.exe
  tests:
  - script:
    - pixi-build-mojo help
- package:
    name: pixi-build-python
  inherit: pixi-build
  build:
    files:
    - bin/pixi-build-python
    - Library/bin/pixi-build-python.exe
  tests:
  - script:
    - pixi-build-python help
- package:
    name: pixi-build-r
  inherit: pixi-build
  build:
    files:
    - bin/pixi-build-r
    - Library/bin/pixi-build-r.exe
  tests:
  - script:
    - pixi-build-r help
- package:
    name: pixi-build-ros
  inherit: pixi-build
  build:
    files:
    - bin/pixi-build-ros
    - Library/bin/pixi-build-ros.exe
  tests:
  - script:
    - pixi-build-ros help
- package:
    name: pixi-build-rust
  inherit: pixi-build
  build:
    files:
    - bin/pixi-build-rust
    - Library/bin/pixi-build-rust.exe
  tests:
  - script:
    - pixi-build-rust help

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
