context:
  version: 0.55.0
  sha256: fcf3dc002573980780b27e92d2f10e1b23f82bbb0df3c127bbfdabe0813dfa75

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://codeload.github.com/prefix-dev/pixi/tar.gz/v${{ version }}
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - 0001-customize.patch
- url: https://codeload.github.com/conda/rattler/tar.gz/rattler-v0.37.3
  sha256: 935818530950ba962ec1ae06fbe670e1378f98c5b6c32b6b01838609ca1c267f
  target_directory: rattler
  patches:
  - 0001-strip-dquotes.patch
- url: https://codeload.github.com/astral-sh/uv/tar.gz/0.8.5
  sha256: 611e2ad9b20f2462bf30632d2d2dc0eae865046e058c8c8f7180ddb0cd4e2b26
  target_directory: uv
  patches:
  - 0001-conda-build.patch
- url: https://codeload.github.com/astral-sh/rs-async-zip/tar.gz/c909fda63fcafe4af496a07bfda28a5aae97e58d
  sha256: 8fc71e219a505af64d9c616f7940d24c1b38dc1f54c03d32cb34ba84930f3e1d
  target_directory: rs-async-zip
- url: https://codeload.github.com/astral-sh/pubgrub/tar.gz/06ec5a5f59ffaeb6cf5079c6cb184467da06c9db
  sha256: 7c39356749ea0084a75ef64f59890b2ce395d5f4492cb32474573650b7e52685
  target_directory: pubgrub
- url: https://codeload.github.com/astral-sh/reqwest-middleware/tar.gz/ad8b9d332d1773fde8b4cd008486de5973e0a3f8
  sha256: 5ff23bcb5f724323cb2c7d6a9b597a9a05ce06295b1a7e2c667d378099f1a8d7
  target_directory: reqwest-middleware
- url: https://codeload.github.com/astral-sh/tl/tar.gz/6e25b2ee2513d75385101a8ff9f591ef51f314ec
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: tl
- if: win
  then:
  - url: https://github.com/Chuyu-Team/VC-LTL5/releases/download/v5.2.2/VC-LTL-Binary.7z
    sha256: 04aa46a7d2af655bcf42c4937504525eb7e66a75910ed42fd25a1cdcec587df0
    target_directory: vc_ltl
- if: win
  then:
  - url: https://github.com/Chuyu-Team/YY-Thunks/releases/download/v1.1.8/YY-Thunks-Objs.zip
    sha256: 2c5ef3c2e8a3abc366ed1ab233f46e60951eb1250a5f1a5b1527ed6983bf4e74
    target_directory: yy_thunks

build:
  number: 0
  script:
  - if: win
    then:
    - set "VC_LTL=%SRC_DIR%\vc_ltl"
    - set "YY_THUNKS=%SRC_DIR%\yy_thunks"
    - cargo install --config target.x86_64-pc-windows-msvc.linker=\"link\" --features performance --locked --no-track --path pixi/crates/pixi --profile dist --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --features performance --locked --no-track --path pixi/crates/pixi --profile dist --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - rust >=1.89.0
  - if: linux
    then: diffutils
  - if: linux
    then: make
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  - if: win
    then: 7zip

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
