context:
  version: 0.36.0
  sha256: 9fcc24d6f1bf868ab4f62f50eef785df28e7d3ab1a159afcfbbb9b23fa0ddaa5

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://github.com/prefix-dev/pixi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - 0001-customize.patch
- url: https://github.com/astral-sh/uv/archive/refs/tags/0.4.30.tar.gz
  sha256: 0f74a570e52affd82ff7987ade2553e144a326e7ff58de24ab4242999a3dc931
  target_directory: uv
  patches:
  - 0001-conda-build.patch
- url: https://github.com/charliermarsh/rs-async-zip/archive/011b24604fa7bc223daaad7712c0694bac8f0a87.tar.gz
  sha256: 68494b68d07df2a36d85e7e5e3cf39ccd4caa49876f874e0171610aac2e62730
  target_directory: uv/rs-async-zip
- url: https://github.com/astral-sh/pubgrub/archive/95e1390399cdddee986b658be19587eb1fdb2d79.tar.gz
  sha256: 96f308d260d015065de2746906f10b242473380e0a3acd457015759c034b5e5c
  target_directory: uv/pubgrub
- url: https://github.com/TrueLayer/reqwest-middleware/archive/d95ec5a99fcc9a4339e1850d40378bbfe55ab121.tar.gz
  sha256: 9ea16dba8853cfecd1d1e3b8727eb2e904488e745c7f5efa813e7dac34c893f2
  target_directory: reqwest-middleware
- url: https://github.com/charliermarsh/tl/archive/6e25b2ee2513d75385101a8ff9f591ef51f314ec.tar.gz
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: uv/tl

build:
  number: 0
  script:
  - cd pixi
  - cargo build --profile dist
  - if: win
    then:
    - mklink /H "%LIBRARY_BIN%\pixi.exe" target\dist\pixi.exe
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:4] != 'vs20'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust 1.81.0

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
