context:
  version: 0.43.0
  sha256: 44f781049bd5d01f550fb17cc3880a36df29bad0429453c6527ee316fc0bad20

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://github.com/prefix-dev/pixi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - 0001-customize.patch
- url: https://github.com/conda/rattler/archive/refs/tags/rattler-v0.33.3.tar.gz
  sha256: 68f6513db56c10fbf363924e4b4f40f9bc218f9044b949723224bfdc82addb9d
  target_directory: rattler
  patches:
  - 0001-strip-dquotes.patch
- url: https://github.com/astral-sh/uv/archive/refs/tags/0.6.1.tar.gz
  sha256: 70118971a2b6b7b6ac8e028b2505178b6a75ae77c314a60ff8403645e1ef7d78
  target_directory: uv
  patches:
  - 0001-conda-build.patch
- url: https://github.com/charliermarsh/rs-async-zip/archive/c909fda63fcafe4af496a07bfda28a5aae97e58d.tar.gz
  sha256: 8fc71e219a505af64d9c616f7940d24c1b38dc1f54c03d32cb34ba84930f3e1d
  target_directory: uv/rs-async-zip
- url: https://github.com/astral-sh/pubgrub/archive/b70cf707aa43f21b32f3a61b8a0889b15032d5c4.tar.gz
  sha256: 64b53dc8b30240d6636cab321750f786e7f50594f0403a1f96b6e8e235014d0a
  target_directory: uv/pubgrub
- url: https://github.com/astral-sh/tl/archive/6e25b2ee2513d75385101a8ff9f591ef51f314ec.tar.gz
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: uv/tl

build:
  number: 0
  script:
  - if: win
    then:
    - cargo install --no-track --path pixi --profile dist --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --no-track --path pixi --profile dist --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust >=1.85.0
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
