context:
  version: 0.64.0
  sha256: 854448c9736366c32103536bc9220543a65bdae6850ab9250fb39a9fb0897160

recipe:
  name: pixi
  version: ${{ version }}

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

cache:
  source:
  - url: https://codeload.github.com/prefix-dev/pixi/tar.gz/v${{ version }}
    sha256: ${{ sha256 }}
    target_directory: pixi
    patches:
    - 0001-customize.patch
  - url: https://codeload.github.com/conda/rattler/tar.gz/rattler-v0.39.12
    sha256: c3c124cbe4860b71684a4997199e4915641ef4c656c8b27629b09d12b2120306
    target_directory: rattler
    patches:
    - 0001-strip-dquotes.patch
  - url: https://codeload.github.com/prefix-dev/rattler-build/tar.gz/d144acdd068b00d9a6bac5fcbd418f34b796fdf9
    sha256: cff329b2ea82f7cd3a5cb4eae842b25c04924a846adfc082ad622c98308f17d6
    target_directory: rattler-build
    patches:
    - 0001-conda-build.patch

  build:
    script:
    - if: win
      then:
      - cargo install --features performance --locked --no-track --path pixi/crates/pixi --profile dist --root "%LIBRARY_PREFIX%"
      - cargo install --locked --no-track --path pixi/crates/pixi_build_cmake --profile dist --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path pixi/crates/pixi_build_mojo --profile dist --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path pixi/crates/pixi_build_python --profile dist --root "%LIBRARY_PREFIX%"
      - cargo install --frozen --no-track --path pixi/crates/pixi_build_rattler_build --profile dist --root "%LIBRARY_PREFIX%"
      - cargo install --locked --no-track --path pixi/crates/pixi_build_rust --profile dist --root "%LIBRARY_PREFIX%"
      else:
      - cargo install --features performance --locked --no-track --path pixi/crates/pixi --profile dist --root "$PREFIX"
      - cargo install --locked --no-track --path pixi/crates/pixi_build_cmake --profile dist --root "$PREFIX"
      - cargo install --frozen --no-track --path pixi/crates/pixi_build_mojo --profile dist --root "$PREFIX"
      - cargo install --frozen --no-track --path pixi/crates/pixi_build_python --profile dist --root "$PREFIX"
      - cargo install --frozen --no-track --path pixi/crates/pixi_build_rattler_build --profile dist --root "$PREFIX"
      - cargo install --locked --no-track --path pixi/crates/pixi_build_rust --profile dist --root "$PREFIX"

  requirements:
    build:
    - ${{ compiler('c') }}
    - rust >=1.90.0
    - if: linux
      then: diffutils
    - if: linux
      then: make
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}

outputs:
- package:
    name: pixi
  build:
    files:
    - bin/pixi
    - Library/bin/pixi.exe
  tests:
  - script:
    - pixi -V
- package:
    name: pixi-build-cmake
  build:
    files:
    - bin/pixi-build-cmake
    - Library/bin/pixi-build-cmake.exe
  tests:
  - script:
    - pixi-build-cmake help
- package:
    name: pixi-build-mojo
  build:
    files:
    - bin/pixi-build-mojo
    - Library/bin/pixi-build-mojo.exe
  tests:
  - script:
    - pixi-build-mojo help
- package:
    name: pixi-build-python
  build:
    files:
    - bin/pixi-build-python
    - Library/bin/pixi-build-python.exe
  tests:
  - script:
    - pixi-build-python help
- package:
    name: pixi-build-rattler-build
  build:
    files:
    - bin/pixi-build-rattler-build
    - Library/bin/pixi-build-rattler-build.exe
  tests:
  - script:
    - pixi-build-rattler-build help
- package:
    name: pixi-build-rust
  build:
    files:
    - bin/pixi-build-rust
    - Library/bin/pixi-build-rust.exe
  tests:
  - script:
    - pixi-build-rust help

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
