context:
  version: 0.60.0
  sha256: a8db25102a5203d0175e0cee0144d8cd7c525bf6a8556ad90ad07c54361667d6

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://codeload.github.com/prefix-dev/pixi/tar.gz/v${{ version }}
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - 0001-customize.patch
- url: https://codeload.github.com/conda/rattler/tar.gz/rattler_lock-v0.26.7
  sha256: f0056554c19766d1b19fdee808d6c12c7000e0a628a8e55343bc540b8a8ba676
  target_directory: rattler
  patches:
  - 0001-strip-dquotes.patch
- if: win
  then:
  - url: https://github.com/Chuyu-Team/VC-LTL5/releases/download/v5.2.2/VC-LTL-Binary.7z
    sha256: 04aa46a7d2af655bcf42c4937504525eb7e66a75910ed42fd25a1cdcec587df0
    target_directory: vc_ltl
- if: win
  then:
  - url: https://github.com/Chuyu-Team/YY-Thunks/releases/download/v1.1.9/YY-Thunks-Objs.zip
    sha256: c53b87f83a3a1322de22195ee43fca590e757369b713304a4ce4fcaad532f8b7
    target_directory: yy_thunks

build:
  number: 0
  script:
  - if: win
    then:
    - set "VC_LTL=%SRC_DIR%\vc_ltl"
    - set "YY_THUNKS=%SRC_DIR%\yy_thunks"
    - cargo install --features performance --locked --no-track --path pixi/crates/pixi --profile dist --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --features performance --locked --no-track --path pixi/crates/pixi --profile dist --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - rust >=1.89.0
  - if: linux
    then: diffutils
  - if: linux
    then: make
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  - if: win
    then: 7zip

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
