context:
  version: 0.29.0
  sha256: f478b78b26708748455a843623fe5bd134508395dfa3d540de83fd8c05d43dc6

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://github.com/prefix-dev/pixi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - 0001-customize.patch
- url: https://github.com/astral-sh/uv/archive/refs/tags/0.4.0.tar.gz
  sha256: d4a734b4179ac56aeb23b986eb5e2324360eab45080d4d6fca1afa18b20828f8
  target_directory: uv
  patches:
  - 0001-conda-build.patch
- url: https://github.com/charliermarsh/rs-async-zip/archive/011b24604fa7bc223daaad7712c0694bac8f0a87.tar.gz
  sha256: 68494b68d07df2a36d85e7e5e3cf39ccd4caa49876f874e0171610aac2e62730
  target_directory: uv/rs-async-zip
- url: https://github.com/astral-sh/pubgrub/archive/388685a8711092971930986644cfed152d1a1f6c.tar.gz
  sha256: 5383f8d836053a7b62408fb09d29ffaf862dea46d7045184a86c0cd9a5d5ee46
  target_directory: uv/pubgrub
- url: https://github.com/astral-sh/reqwest-middleware/archive/5e3eaf254b5bd481c75d2710eed055f95b756913.tar.gz
  sha256: 4370f28fd0baa6231c50de27ee130488e85ab54136d740b7a13375246119c580
  target_directory: reqwest-middleware
- url: https://github.com/charliermarsh/tl/archive/6e25b2ee2513d75385101a8ff9f591ef51f314ec.tar.gz
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: uv/tl

build:
  number: 0
  script:
  - cd pixi
  - cargo build --release
  - if: win
    then:
    - mklink /H "%LIBRARY_BIN%\pixi.exe" target\release\pixi.exe
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:4] != 'vs20'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust 1.80.0

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
