context:
  version: 0.73.0
  sha256: d47b057f3a5ffc3541c38ac100e07ab65a69022aa900e413cf34a79bb1bd5c28

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://codeload.github.com/prefix-dev/pixi/tar.gz/v${{ version }}
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - changes.patch
- url: https://codeload.github.com/conda/rattler/tar.gz/rattler-v0.47.0
  sha256: 50853673f542ff9f10cda0c7c6c1fdeb41c016824d8cc40336b0e33103cdb2e9
  target_directory: rattler
  patches:
  - 0001-strip-dquotes.patch

build:
  number: 0
  script:
  - if: win
    then:
    - set AWS_LC_SYS_PREBUILT_NASM=0
    - cargo install --features performance --locked --no-track --path pixi/crates/pixi --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --features performance --locked --no-track --path pixi/crates/pixi --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - rust >=1.94.0
  - if: linux
    then: diffutils
  - if: linux
    then: make
  - nasm
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
