context:
  version: 0.39.1
  sha256: a27bcc2cad16132124696b9ea16b918424af1c79f52e159a9f2d588bb0cbd0cb

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://github.com/prefix-dev/pixi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - 0001-customize.patch
- url: https://github.com/conda/rattler/archive/refs/tags/rattler-v0.28.5.tar.gz
  sha256: ef65d08c41f741f0abd2ede9a8b687b3ca2c1db479fade9f7bdc6e45a8622300
  target_directory: rattler
  patches:
  - 0001-strip-dquotes.patch
- url: https://github.com/astral-sh/uv/archive/refs/tags/0.5.6.tar.gz
  sha256: 7be2246b0f8f54f3746aff1da35bb3bb995974714d7bc625300a0f91d6f5dae4
  target_directory: uv
  patches:
  - 0001-conda-build.patch
- url: https://github.com/charliermarsh/rs-async-zip/archive/c909fda63fcafe4af496a07bfda28a5aae97e58d.tar.gz
  sha256: 8fc71e219a505af64d9c616f7940d24c1b38dc1f54c03d32cb34ba84930f3e1d
  target_directory: uv/rs-async-zip
- url: https://github.com/astral-sh/pubgrub/archive/57832d0588fbb7aab824813481104761dc1c7740.tar.gz
  sha256: d6bcd72961f50efeb32358365470de44a3fee0fa8221ca31ea7420395ff5d055
  target_directory: uv/pubgrub
- url: https://github.com/astral-sh/tl/archive/6e25b2ee2513d75385101a8ff9f591ef51f314ec.tar.gz
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: uv/tl

build:
  number: 0
  script:
  - cd pixi
  - cargo build --profile dist
  - if: win
    then:
    - mklink /H "%LIBRARY_BIN%\pixi.exe" target\dist\pixi.exe
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:4] != 'vs20'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust 1.81.0

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
