context:
  version: 0.41.3
  sha256: 9926d31fc524867f989285bb8f4d09f28750224437c0351dd237de75af2b2fb8

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://github.com/prefix-dev/pixi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - 0001-customize.patch
- url: https://github.com/conda/rattler/archive/refs/tags/rattler-v0.31.1.tar.gz
  sha256: 16c9ff4cc701f2c72f36130f5f53f65a6e44b0d092ff4a7d9794f0de7c83e866
  target_directory: rattler
  patches:
  - 0001-strip-dquotes.patch
- url: https://github.com/astral-sh/uv/archive/refs/tags/0.5.29.tar.gz
  sha256: f562a58d4c5e405664936cc4cab815bfea8a7b4bc4702c0a1735b23ea6cf8643
  target_directory: uv
  patches:
  - 0001-conda-build.patch
- url: https://github.com/charliermarsh/rs-async-zip/archive/c909fda63fcafe4af496a07bfda28a5aae97e58d.tar.gz
  sha256: 8fc71e219a505af64d9c616f7940d24c1b38dc1f54c03d32cb34ba84930f3e1d
  target_directory: uv/rs-async-zip
- url: https://github.com/astral-sh/pubgrub/archive/b70cf707aa43f21b32f3a61b8a0889b15032d5c4.tar.gz
  sha256: 64b53dc8b30240d6636cab321750f786e7f50594f0403a1f96b6e8e235014d0a
  target_directory: uv/pubgrub
- url: https://github.com/astral-sh/tl/archive/6e25b2ee2513d75385101a8ff9f591ef51f314ec.tar.gz
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: uv/tl

build:
  number: 0
  script:
  - cd pixi
  - cargo build --profile dist
  - if: win
    then:
    - mklink /H "%LIBRARY_BIN%\pixi.exe" target\dist\pixi.exe
    else:
    - mkdir -p "$PREFIX/bin"
    - ln target/dist/pixi "$PREFIX/bin"
  skip:
  - build_platform != target_platform
  - win and compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust ==1.84.0
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
