context:
  version: 0.40.2
  sha256: 90015ae7a3dfa2458f44e1867fff14215e4b1d21de1f3c0da85b89f5728cbe42

package:
  name: pixi
  version: ${{ version }}

source:
- url: https://github.com/prefix-dev/pixi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: pixi
  patches:
  - 0001-customize.patch
- url: https://github.com/conda/rattler/archive/refs/tags/rattler-v0.28.11.tar.gz
  sha256: e8fcedd1775d9f1656e75ed4ecefab0820617711f96e64c5373415f5cc1e983b
  target_directory: rattler
  patches:
  - 0001-strip-dquotes.patch
- url: https://github.com/wolfv/uv/archive/refs/heads/ignore-rayon-init.tar.gz
  sha256: 3653b29fe76492f87ef0459975f8972d2fc7ad254280bfd2ada040a0aa207bcb
  target_directory: uv
  patches:
  - 0001-conda-build.patch
- url: https://github.com/charliermarsh/rs-async-zip/archive/c909fda63fcafe4af496a07bfda28a5aae97e58d.tar.gz
  sha256: 8fc71e219a505af64d9c616f7940d24c1b38dc1f54c03d32cb34ba84930f3e1d
  target_directory: uv/rs-async-zip
- url: https://github.com/astral-sh/pubgrub/archive/57832d0588fbb7aab824813481104761dc1c7740.tar.gz
  sha256: d6bcd72961f50efeb32358365470de44a3fee0fa8221ca31ea7420395ff5d055
  target_directory: uv/pubgrub
- url: https://github.com/astral-sh/tl/archive/6e25b2ee2513d75385101a8ff9f591ef51f314ec.tar.gz
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: uv/tl

build:
  number: 0
  script:
  - cd pixi
  - cargo build --profile dist
  - if: win
    then:
    - mklink /H "%LIBRARY_BIN%\pixi.exe" target\dist\pixi.exe
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust ==1.81.0

tests:
- script:
  - pixi -V

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: pixi/LICENSE
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
