context:
  version: 0.3.10
  sha256: 43334dbcd764127b57b9ddf5d0860fa1c464ac4757cae8984ddfbd5a3839ea82

package:
  name: pixi-build-rattler-build
  version: ${{ version }}

source:
  url: https://codeload.github.com/prefix-dev/pixi/tar.gz/pixi-build-rattler-build-v${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch

build:
  number: 0
  script:
  - if: win
    then:
    - set AWS_LC_SYS_PREBUILT_NASM=0
    - cargo install --locked --no-track --path crates/pixi_build_rattler_build --profile dist --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --locked --no-track --path crates/pixi_build_rattler_build --profile dist --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - if: linux
    then: diffutils
  - if: linux
    then: make
  - nasm
  - rust >=1.90.0
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}

tests:
- script:
  - pixi-build-rattler-build help

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pixi build backend to build recipe.yaml files.
