context:
  name: tqdm
  version: 4.67.1
  sha256: f8aef9c52c08c13a65f30ea34f4e5aac3fd1a34959879d7e59e63027286627f2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[:1] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-update-tqdm.rich-to-better-match-tqdm.std.patch
  - 0002-refactor-close-refresh-on-last-display-1580.patch
  - 0003-only-force-refresh-on-close-if-jupyter-1579.patch
  - 0004-use-tqdm-s-elapsed-instead-of-Task.elapsed-property.patch

build:
  noarch: python
  number: 0
  python:
    entry_points:
    - tqdm = tqdm.cli:main
  script: pip install .

requirements:
  host:
  - pip
  - python >=3.7.0
  - setuptools >=42.0.0
  - setuptools-scm >=3.4.0
  - toml
  - wheel
  run:
  - colorama
  - python >=3.7.0

tests:
- script:
  - tqdm -v

about:
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
