context:
  version: 0.6.16
  sha256: 506c5970777ace5840c2d3a90b507265aab24749469ba03f88526c4b6f9bfa70

package:
  name: uv
  version: ${{ version }}

source:
- url: https://github.com/astral-sh/uv/archive/refs/tags/${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: uv
  patches:
  - 0001-customize.patch
- url: https://github.com/charliermarsh/rs-async-zip/archive/c909fda63fcafe4af496a07bfda28a5aae97e58d.tar.gz
  sha256: 8fc71e219a505af64d9c616f7940d24c1b38dc1f54c03d32cb34ba84930f3e1d
  target_directory: rs-async-zip
- url: https://github.com/astral-sh/pubgrub/archive/b70cf707aa43f21b32f3a61b8a0889b15032d5c4.tar.gz
  sha256: 64b53dc8b30240d6636cab321750f786e7f50594f0403a1f96b6e8e235014d0a
  target_directory: pubgrub
- url: https://github.com/astral-sh/tl/archive/6e25b2ee2513d75385101a8ff9f591ef51f314ec.tar.gz
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: tl
- if: win
  then:
  - url: https://github.com/Chuyu-Team/VC-LTL5/releases/download/v5.2.1/VC-LTL-Binary.7z
    sha256: 0b0b17b7a4ed993701208b2eaeba91f3acf2f1b5402430b52ac7bfbca2519464
- if: win
  then:
  - url: https://github.com/Chuyu-Team/YY-Thunks/releases/download/v1.1.6/YY-Thunks-Objs.zip
    sha256: fa4de6bda69f476907f780f63f3dda792537a2e3236cd23043a490c6b91cb0b5
    target_directory: yy_thunks

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - rust >=1.85.0
  - if: linux
    then: diffutils
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  - if: win
    then: 7zip

tests:
- script:
  - uv -V

about:
  license: Apache-2.0 OR MIT
  license_file:
  - uv/LICENSE-APACHE
  - uv/LICENSE-MIT
  summary: An extremely fast Python package installer and resolver, written in Rust.
