context:
  version: 0.10.10
  sha256: ba4082c92c97e0cc5ac0bc48a2783bc5026c8a14a768ecfb5f7012223a5e90ac

package:
  name: uv
  version: ${{ version }}

source:
  url: https://codeload.github.com/astral-sh/uv/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  patches:
  - changes.patch

build:
  number: 0
  script:
  - if: win
    then:
    - cargo install --features windows-gui-bin --locked --no-track --path crates\uv --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --locked --no-track --path crates/uv --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - rust >=1.91.0
  - if: linux
    then: diffutils
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}

tests:
- script:
  - uv -V

about:
  license: Apache-2.0 OR MIT
  license_file:
  - LICENSE-APACHE
  - LICENSE-MIT
  summary: An extremely fast Python package installer and resolver, written in Rust.
