context:
  version: 0.9.5
  sha256: 9fd1dd030b37b51dcf79b582ea77a911eeb4015a00669bd3047d3b6adea37ba8

package:
  name: uv
  version: ${{ version }}

source:
- url: https://codeload.github.com/astral-sh/uv/tar.gz/${{ version }}
  sha256: ${{ sha256 }}
  target_directory: uv
  patches:
  - 0001-customize.patch
- if: win
  then:
  - url: https://github.com/Chuyu-Team/VC-LTL5/releases/download/v5.2.2/VC-LTL-Binary.7z
    sha256: 04aa46a7d2af655bcf42c4937504525eb7e66a75910ed42fd25a1cdcec587df0
    target_directory: vc_ltl
- if: win
  then:
  - url: https://github.com/Chuyu-Team/YY-Thunks/releases/download/v1.1.8/YY-Thunks-Objs.zip
    sha256: 2c5ef3c2e8a3abc366ed1ab233f46e60951eb1250a5f1a5b1527ed6983bf4e74
    target_directory: yy_thunks

build:
  number: 0
  script:
  - if: win
    then:
    - set "VC_LTL=%SRC_DIR%\vc_ltl"
    - set "YY_THUNKS=%SRC_DIR%\yy_thunks"
    - cargo install --config target.x86_64-pc-windows-msvc.linker=\"link\" --features windows-gui-bin --locked --no-track --path uv\crates\uv --root "%LIBRARY_PREFIX%"
    else:
    - cargo install --locked --no-track --path uv/crates/uv --root "$PREFIX"
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - rust >=1.89.0
  - if: linux
    then: diffutils
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  - if: win
    then: 7zip

tests:
- script:
  - uv -V

about:
  license: Apache-2.0 OR MIT
  license_file:
  - uv/LICENSE-APACHE
  - uv/LICENSE-MIT
  summary: An extremely fast Python package installer and resolver, written in Rust.
