context:
  version: 0.7.3
  sha256: ad6dbd387c8627571580c81e9e127555d4b91d2bec4578876c5f2505a4cda29c

package:
  name: uv
  version: ${{ version }}

source:
- url: https://github.com/astral-sh/uv/archive/refs/tags/${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  target_directory: uv
  patches:
  - 0001-customize.patch
- url: https://github.com/charliermarsh/rs-async-zip/archive/c909fda63fcafe4af496a07bfda28a5aae97e58d.tar.gz
  sha256: 8fc71e219a505af64d9c616f7940d24c1b38dc1f54c03d32cb34ba84930f3e1d
  target_directory: rs-async-zip
- url: https://github.com/astral-sh/pubgrub/archive/a3b4db3abb1829ce889fb89fa6d157fef529ef7e.tar.gz
  sha256: 3294d1b09d2f99f96fb38a114b54bcfb098e347d5cc14c96f0e356dbc678bcc9
  target_directory: pubgrub
- url: https://github.com/astral-sh/tl/archive/6e25b2ee2513d75385101a8ff9f591ef51f314ec.tar.gz
  sha256: e838bca7cb205e373cd801ce19476a808534a6090fc261aa2ea74dfd9cea68b0
  target_directory: tl
- if: win
  then:
  - url: https://github.com/Chuyu-Team/VC-LTL5/releases/download/v5.2.1/VC-LTL-Binary.7z
    sha256: 0b0b17b7a4ed993701208b2eaeba91f3acf2f1b5402430b52ac7bfbca2519464
- if: win
  then:
  - url: https://github.com/Chuyu-Team/YY-Thunks/releases/download/v1.1.7/YY-Thunks-Objs.zip
    sha256: c3066f3f074ebc2a89b2def5f427bdea238dee17349d2bab579af519781691ab
    target_directory: yy_thunks

build:
  number: 0
  skip:
  - build_platform != target_platform
  - win and not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - rust >=1.85.0
  - if: linux
    then: diffutils
  - if: microarch_level|int > 0
    then: x86_64-microarch-level ==${{ microarch_level }}
  - if: win
    then: 7zip

tests:
- script:
  - uv -V

about:
  license: Apache-2.0 OR MIT
  license_file:
  - uv/LICENSE-APACHE
  - uv/LICENSE-MIT
  summary: An extremely fast Python package installer and resolver, written in Rust.
