context:
  version: 9.8.1
  sha256: 5782ffbd602ffa807009095b4b10de84f1bbcf7dd77a831fa1bcd161660b3768

package:
  name: openssh
  version: ${{ version }}p1

source:
- url: https://github.com/PowerShell/openssh-portable/archive/refs/tags/v${{ version }}.0.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch
- url: https://github.com/PowerShell/libfido2/releases/download/1.15.0/libfido2.zip
  sha256: 2d9bf95672d7324f970c7c8810a9abcfd6e803e2aa1c6d63aef9a51e1bc901ea
  target_directory: contrib/win32/openssh/libfido2
- url: https://github.com/PowerShell/LibreSSL/releases/download/V3.9.2.0/LibreSSL.zip
  sha256: 53273d1e28cc66a7f363bccce94677e31f060330285dcb1ded11337aea9251d4
  target_directory: contrib/win32/openssh/LibreSSL
- url: https://github.com/PowerShell/zlib/releases/download/V1.3.1/zlib.zip
  sha256: cf6c5e752ade112ff2de981553db21c0b077123243e771cc9bc335e725eb5c75
  target_directory: contrib/win32/openssh/zlib

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:3] == 'gcc'

requirements:
  build:
  - ${{ compiler('c') }}
  host:
  - zlib

tests:
- script:
  - ssh -V

about:
  license_file: LICENCE
  summary: A suite of secure networking utilities based on the SSH protocol
