context:
  version: 9.8.3
  sha256: 5114e573716f2c9500742728dd673753e0efe1c80753f15feccef75cc46cc1ee

package:
  name: openssh
  version: ${{ version }}p2

source:
- url: https://codeload.github.com/PowerShell/openssh-portable/tar.gz/v${{ version }}.0
  sha256: ${{ sha256 }}
  patches:
  - 0001-conda-build.patch
  - 0002-customize.patch
- url: https://github.com/PowerShell/libfido2/releases/download/1.15.0/libfido2.zip
  sha256: 2d9bf95672d7324f970c7c8810a9abcfd6e803e2aa1c6d63aef9a51e1bc901ea
  target_directory: contrib/win32/openssh/libfido2
- url: https://github.com/PowerShell/LibreSSL/releases/download/V4.0.0.0/LibreSSL.zip
  sha256: 91ae2d5ffe5c3db58280cc9ed658d110a702fe009f413e60889441b6231a0670
  target_directory: contrib/win32/openssh/LibreSSL
- url: https://github.com/PowerShell/zlib/releases/download/V1.3.1/zlib.zip
  sha256: cf6c5e752ade112ff2de981553db21c0b077123243e771cc9bc335e725eb5c75
  target_directory: contrib/win32/openssh/zlib

build:
  number: 0
  script:
  - cd contrib\win32\openssh
  - sed -i -e "s MultiThreaded< MultiThreadedDLL< " -e "s %%(PreprocessorDefinitions) HAVE_STRNLEN;%%(PreprocessorDefinitions) " -e "s >Spectre< >false< " config.vcxproj keygen.vcxproj libssh.vcxproj openbsd_compat.vcxproj scp.vcxproj sftp-server.vcxproj sftp.vcxproj ssh-add.vcxproj ssh-agent.vcxproj ssh-keyscan.vcxproj ssh-pkcs11-helper.vcxproj ssh-shellhost.vcxproj ssh-sk-helper.vcxproj ssh.vcxproj sshd-session.vcxproj sshd.vcxproj unittest-bitmap.vcxproj unittest-hostkeys.vcxproj unittest-kex.vcxproj unittest-match.vcxproj unittest-misc.vcxproj unittest-sshbuf.vcxproj unittest-sshkey.vcxproj unittest-utf8.vcxproj unittest-win32compat.vcxproj win32iocompat.vcxproj
  - msbuild -p:Configuration=Release;Platform=x64 Win32-OpenSSH.sln
  - mklink /H "%LIBRARY_BIN%\libcrypto.dll" LibreSSL\bin\desktop\X64\libcrypto.dll
  - copy "%SRC_DIR%\bin\x64\Release\*.exe" "%LIBRARY_BIN%"
  - md "%PREFIX%\etc\conda"
  - cd "%PREFIX%\etc\conda"
  - md activate.d deactivate.d
  - copy "%RECIPE_DIR%\*_activate-win.*" activate.d
  - copy "%RECIPE_DIR%\*_deactivate-win.*" deactivate.d
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - m2-sed
  host:
  - zlib

tests:
- script:
  - ssh -V

about:
  license_file: LICENCE
  summary: A suite of secure networking utilities based on the SSH protocol
