context:
  version: 6.1.1
  sha256: 7c1ebea95d815e49c1e60c7ee816410dec73a81b8ac002b276780d2f9048e598

package:
  name: ffmpeg
  version: '{{ version }}'

source:
- url: https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n{{ version.removesuffix('.0') }}.tar.gz
  sha256: '{{ sha256 }}'
  patches:
  - 0001-customize.patch

build:
  include_recipe: false
  number: 0
  script_env:
    CHERE_INVOKING: '1'
    MSYS2_PATH_TYPE: inherit
  skip:
  - not win64
  - build_platform != target_platform

requirements:
  build:
  - "{{ compiler('c') }}"
  - nasm
  - pkg-config
  host:
  - ffnvcodec-headers
  - posix
  - sdl2 >=2.23.1
  run:
  - sdl2

test:
  commands:
  - ffmpeg -version
  - ffplay -version
  - ffprobe -version

about:
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.GPLv2
  summary: Cross-platform solution to record, convert and stream audio and video.
