context:
  version: 7.0.2
  sha256: 8646515b638a3ad303e23af6a3587734447cb8fc0a0c064ecdb8e95c4fd8b389

package:
  name: ffmpeg
  version: ${{ version }}

source:
- url: https://ffmpeg.org/releases/ffmpeg-${{ version|trim('0')|trim('.') }}.tar.xz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch

build:
  number: 0
  script:
    env:
      MSYS2_PATH_TYPE: inherit
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:3] == 'gcc'

requirements:
  build:
  - ${{ compiler('c') }}
  - nasm
  - pkg-config
  host:
  - ffnvcodec-headers
  - posix
  - sdl2 >=2.23.1

tests:
- script:
  - ffmpeg -version
  - ffplay -version
  - ffprobe -version

about:
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.GPLv2
  summary: Cross-platform solution to record, convert and stream audio and video.
