context:
  version: 7.1.0
  sha256: 40973d44970dbc83ef302b0609f2e74982be2d85916dd2ee7472d30678a7abe6

package:
  name: ffmpeg
  version: ${{ version }}

source:
- url: https://ffmpeg.org/releases/ffmpeg-${{ version|trim('0')|trim('.') }}.tar.xz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch

build:
  number: 0
  script:
    env:
      MSYS2_PATH_TYPE: inherit
  skip:
  - not win
  - build_platform != target_platform
  - compiler('c')[:2] != 'vs'

requirements:
  build:
  - ${{ compiler('c') }}
  - m2-base
  - nasm
  - pkg-config
  host:
  - ffnvcodec-headers
  - sdl2 >=2.23.1

tests:
- script:
  - ffmpeg -version
  - ffplay -version
  - ffprobe -version

about:
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.GPLv2
  summary: Cross-platform solution to record, convert and stream audio and video.
