context:
  version: 8.0.0
  sha256: b2751fccb6cc4c77708113cd78b561059b6fa904b24162fa0be2d60273d27b8e

package:
  name: ffmpeg
  version: ${{ version }}

source:
- url: https://ffmpeg.org/releases/ffmpeg-${{ version|trim('0')|trim('.') }}.tar.xz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch

build:
  number: 0
  script:
    content:
    - bash -el "%RECIPE_DIR%\build.sh"
    env:
      MSYS2_PATH_TYPE: inherit
  skip:
  - not win
  - build_platform != target_platform
  - not (compiler('c') is startingwith('vs'))

requirements:
  build:
  - ${{ compiler('c') }}
  - m2-base
  - m2-diffutils
  - m2-make
  host:
  - ffnvcodec-headers
  - libiconv
  - nasm
  - pkg-config
  - sdl2 >=2.23.1

tests:
- script:
  - ffmpeg -version
  - ffplay -version
  - ffprobe -version

about:
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.GPLv2
  summary: Cross-platform solution to record, convert and stream audio and video.
