context:
  version: 7.0.1
  sha256: 8dab1da0c7ebccb2dce99265901f22ac40f8e0fbbe4a89a368d7645f2e79caa0

package:
  name: ffmpeg
  version: ${{ version }}

source:
- url: https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n${{ version|trim('0')|trim('.') }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
  - 0001-customize.patch

build:
  number: 0
  skip:
  - not win
  - build_platform != target_platform

requirements:
  build:
  - ${{ compiler('c') }}
  - nasm
  - pkg-config
  host:
  - ffnvcodec-headers
  - posix
  - sdl2 >=2.23.1

tests:
- script:
  - ffmpeg -version
  - ffplay -version
  - ffprobe -version

about:
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.GPLv2
  summary: Cross-platform solution to record, convert and stream audio and video.
